### ISSUE TITLE
Stacktrace when fetching objects using s3 module

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#13732]
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 128, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 398, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 186, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 91, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 154, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 210, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 0
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 128, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 398, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 186, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 91, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/s3.py", line 154, in get
    verify_ssl=verify_ssl)
  File "/usr/lib/python2.7/dist-packages/salt/utils/s3.py", line 210, in query
    items = ET.fromstring(response)
  File "<string>", line 124, in XML
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0
```
When I use return_bin=True or local_file=<blah> it works properly.

**Comment by dmurphy18** [comment]
Noticed that this issue was still open.  Given this was occurring on the develop branch last year, are you still experiencing the issue with recently releases or the current develop branch ?

**Comment by ryan-lane** [comment]
Damn. I really wish I would have put the command I used to get this stacktrace into the bug. I have no idea how to re-test this.

**Comment by dmurphy18** [comment]
It was a year ago.  Can I go ahead and close this and if you have the issue re-occur, we can open a new issue for it on a recent release ?

**Comment by cachedout** [comment]
This is definietely not fixed. The code in question hasn't changed. Please keep this open.

**Comment by rallytime** [comment]
There has been some movement in the code in this area recently and I am thinking this is related to S3 needing AWS Signature Version 4. That was fixed recently within the last two weeks or so with #25420 in the 2015.5 branch. 

I'm highly inclined to say that this is likely fixed as s3 is working for me, in general, and we don't know what command was used to produce this stacktrace.

Thoughts @ryan-lane and @cachedout?

**Comment by ryan-lane** [comment]
I don't remember how to test, so if we think everything is working well, I'm fine with it.

**Comment by rallytime** [comment]
Ok. We can certainly open this again if we run into it and we have a more reproducible way to test. Thanks!

**Comment by davidwright** [comment]
This is still happening for me in salt-call 2017.7.2 (Nitrogen). It appears to only happen with archive file types. Tar files, zip files and gz files exhibit the issue. Text files and images do not. One other caveat is that I am connecting to a S3 compatible HCP Object Storage not Amazon S3.

**Comment by rallytime** [comment]
@davidwright It is probably worth opening a new issue for this as the original one is nearly 3 years old. Can you open a new issue with all of the relevant information?

**Comment by davidwright** [comment]
Will do. Wasn't sure which way was preferable were the issue matches exactly.

**Comment by rallytime** [comment]
Yeah, no problem. I just bet we'll get more eyes on it with a new issue.
