### ISSUE TITLE
During summary report UnicodeEncodeError: 'latin-1' codec can't encode

### ISSUE THREAD

**Issue by GregMeno** [saltstack/salt#17227]
Steps to reproduce:

```
sudo salt-call cmd.run 'echo "Je peux manger du verre, ça ne me fait pas mal."'
```

or

```
sudo salt-call cmd.run 'echo "私はガラスを食べられます。それは私を傷つけません。"'

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 26798-26800: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 148, in run
    self.opts)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 49, in display_output
    print(display_data)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 26798-26800: ordinal not in range(256)
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 148, in run
    self.opts)
  File "/usr/lib/pymodules/python2.7/salt/output/__init__.py", line 49, in display_output
    print(display_data)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 26798-26800: ordinal not in range(256)
vagrant@precise64:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=en_US

vagrant@precise64:~$ salt-call --version
salt-call 2014.1.13 (Hydrogen)
```
I downgraded to 2014.1.10 and it works fine. Seems like states that print unicode are causing a problem when salt tries to report the final state summary

**Comment by rallytime** [comment]
@dmick Sorry for the late response. The 2014.1 branch is no longer supported, so the fix went directly into 2014.7. 

Also, thanks for the followup @ryepup. Have you seen this error in any other places, or was it just a result of the corrupt registry causing package problems? I am fairly certain this bug is fixed as we haven't heard anything about it since those latest fixes went in, but it would be good to have some verification, since I was able to actually reproduce the error.

**Comment by ryepup** [comment]
@rallytime I had boiled down my error to encoding problems in the command module, unrelated to packages. See the `cmd.run_all` cases above.

I just tried running it again on 2014.7.1, and while I don't get errors, I wouldn't call the windows behavior correct:

    $ salt "windows"" cmd.run 'echo "Îñ?érñå?îöñå?îžå?îöñ"' shell=powershell
    windows:
        AZAñ?AcrAñA?ArAAñA?Ar_A?ArAAñ
    $ salt "windows" cmd.run 'echo "Îñ?érñå?îöñå?îžå?îöñ"'
    windows:
        "AZAñ?AcrAñA?ArAAñA?Ar_A?ArAAñ"

Linux looks great:

    $ salt "linux" cmd.run 'echo "Îñ?érñå?îöñå?îžå?îöñ"'
    linux:
        Îñ?érñå?îöñå?îžå?îöñ

**Comment by jfindlay** [comment]
@s0undt3ch

**Comment by ssgward** [comment]
@GregMeno - Can this issue be closed or is there still an issue within salt?

**Comment by GregMeno** [comment]
@ssgward I will check 2014.7 and  2015.5 later today.
