### ISSUE TITLE
pkgrepo - Failed to configure repo "...": 'int' object is not iterable

### ISSUE THREAD

**Issue by bogdanr** [saltstack/salt#20190]
Hello,

I am adding a repo with salt 2014.1.13:

```
nodesource:
  pkgrepo.managed:
    - humanname: NodeJs Repository
    - name: deb https://deb.nodesource.com/node wheezy main
    - dist: wheezy
    - file: /etc/apt/sources.list.d/nodesource.list
    - keyid: 68576280
    - keyserver: keys.gnupg.net
```

and it is failing with this error:

```
          ID: nodesource
    Function: pkgrepo.managed
        Name: deb https://deb.nodesource.com/node wheezy main
      Result: False
     Comment: Failed to configure repo 'deb https://deb.nodesource.com/node wheezy main': 'int' object is not iterable
```

A few versions ago this used to work just fine but with version 2014.1.13 it stopped working.

**Comment by babilen** [comment]
You might want to try using "keyid: '68576280'" there.

**Comment by rallytime** [comment]
@bogdanr Thanks for the report. Can you give the suggestion from @babilen a try?

Also, please note that we will not be releasing from the 2014.1 branch anymore now that 2014.7.0 and 2014.7.1 are out. Word of warning though, there was a regression with pkgrepo for Debina/Ubuntu distros in 2014.7.0 that was fixed in 2014.7.1. Therefore, if the suggestion above doesn't resolve your issue, I would suggest upgrading to 2014.7.1 to help solve your issue.

Please let us know if either of those suggestions fixes this problem for you, or if you run in to other problems.

**Comment by GermanG** [comment]
For the record: this error also happens on 2014.7 but babilen's solution works fine, 

Regards.

**Comment by rallytime** [comment]
@GermanG Thanks for following up.

**Comment by ssgward** [comment]
@bogdanr - is this still an issue on the latest version of salt you are using? If not an issue, can this be closed?

**Comment by Unksi** [comment]
I have encountered this with version 2015.8.4 as well, so it seems it is not fixed. However, babilen's solution worked around the problem.

**Comment by rallytime** [comment]
@Unksi Hrm...What distro are you running when you ran into this? This looks like it should have been fixed by #20095 for apt-based systems and this fix is available in all of the 2015.8 releases.
