### ISSUE TITLE
Can't provision instances with Azure on 2015.2

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#20362]
`salt-cloud -p <azure-profile> <minion-name>` was working quite well in 2014.7.0, but when running the same command with the exact same provider and profile files, I am not able to provision a VM with azure. 

It gets through the cloud-service creation step as well as creating the VM. It also installs salt, but fails somewhere quickly thereafter. Here's the final information:
```
[INFO    ] Salt installed on nt-azure-test-3
Error: There was a profile error: Cannot deploy salt in a VM if the 'ssh_keyfile' setting is not set and there is no password set for the vm. Check your provider for the 'change_password' option.
```
Did something in the setup change from 2014.7.0 to 2015.2? I ran this with `-l debug` but that was all of the information that was given in the final moments, so I don't have anything else to show really.

@traxair I think you and @techhat have been in this code most recently. Any thoughts?

```
# salt --versions-report
           Salt: 2015.2.0-121-gbf81188
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```

**Comment by rallytime** [comment]
Alright, I have tracked this down to this change in #19162:
```
for key, value in salt.utils.cloud.bootstrap(vm_, __opts__).items():
        ret.setdefault(key, value)
```
The error is coming from the call to `cloud.bootstrap`. I'll get a fix in for this tomorrow.

**Comment by cachedout** [comment]
Pretty sure @rallytime already fixed this. Closing.

**Comment by rallytime** [comment]
Fixed.

**Comment by patelrahul2040** [comment]
hi every one i have installed halite,logging is also correct but live doc seacr is not enable  
please how to do that ?

**Comment by patelrahul2040** [comment]
if you have any idia please let me know...

**Comment by traxair** [comment]
@rallytime I still get the issue when using the 2015.2rc1 tag...

**Comment by rallytime** [comment]
@traxair Thanks for the update. The fix was made right after 2015.2.0rc1 was tagged. So the fix didn't make it into the first RC. It is fixed in the head of 2015.2 and will be available either in the next RC or the official release on 2015.2
