### ISSUE TITLE
2014.7.0 master could not control 2014.7.1 minion

### ISSUE THREAD

**Issue by wt** [saltstack/salt#20777]
Current "salt --versions":

```
           Salt: 2014.7.1
         Python: 2.6.9 (unknown, Sep 13 2014, 00:25:11)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.4
           Mako: Not Installed
```

I use epel6 packages. Over the weekend, the packages were upgraded in the epel6 repo. I have a pkg.latest that installs the salt-master and salt-minions on my fleet.

When the master upgraded, the init script failed to stop the 2014.7.0 master. As a result that 2014.7.0 master was left running after the package was installed (and also after a cronjob that did "service salt-master restart" had run and after a manual attempt to "service salt-master restart").

Simultaneously, some minions were upgraded to 2014.7.0. I don't know if the package restarted them, but they were successfully restarted by a cron job. When the 2014.7.1 minions were attempting to run scheduled highstates, I would see the following in the logs:

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 437, in handle_func
    ret['return'] = self.functions[func]()
  File "/usr/lib/python2.6/site-packages/salt/modules/state.py", line 325, in highstate
    whitelist=kwargs.get('whitelist')
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2849, in call_highstate
    self.load_dynamic(matches)
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 2394, in load_dynamic
    refresh=False)
  File "/usr/lib/python2.6/site-packages/salt/modules/saltutil.py", line 388, in sync_all
    ret['states'] = sync_states(saltenv, False)
  File "/usr/lib/python2.6/site-packages/salt/modules/saltutil.py", line 269, in sync_states
    ret = _sync('states', saltenv)
  File "/usr/lib/python2.6/site-packages/salt/modules/saltutil.py", line 98, in _sync
    source, sub_env, include_pat=r'E@\.(pyx?|so)$'
  File "/usr/lib/python2.6/site-packages/salt/modules/cp.py", line 416, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 224, in cache_dir
    fn_ = self.cache_file('salt://' + fn_, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 147, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 521, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 991, in get_file
    if not data['data']:
TypeError: string indices must be integers, not str
```

Once I manually killed the old masters (SIGKILL to the pids this time) and restarted the master, the minions started to work. I am sorry, but I don't have any more info.

**Comment by thatch45** [comment]
Thanks @wt we will try to reproduce this and figure out what happened

**Comment by wt** [comment]
No problem.

**Comment by bersace** [comment]
Hi,

I confirm this bug with same versions :

```console
# salt-master --versions-report
           Salt: 2014.7.1
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
# salt-minion --versions-report
           Salt: 2014.7.1
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.4.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: 1.0.0
```

**Comment by cachedout** [comment]
@bersace And does fully restarting the master resolve the issue for you as it did for @wt?

**Comment by cachedout** [comment]
This sounds more like a problem with the system service not fully restarting the salt-master than anything else. What distro is this behaviour being observed on?

**Comment by wt** [comment]
In my case, Amazon Linux.

**Comment by notpeter** [comment]
I'm also seeing this with Ubuntu 14.04.

**Comment by wt** [comment]
Should this be closed?

**Comment by vutny** [comment]
Hi @wt,

2014.7 release is far too old and has its problems which highly possible already fixed in 2015.8.
And RPM post-install scripts are very dummy in general.

I learned from my experience a good practice to upgrade all minions first, schedule execution of the following command (with `at` for example):
```
killall salt-minion; sleep 5; killall -9 salt-minion; service salt-minion start
```

And manually supervision master upgrade after that.

I think you can close the issue.

**Comment by prokashyap** [comment]
```
import sys
import ruamel.yaml
import os
yaml = ruamel.yaml.YAML()
with open('deployment.yaml') as fp:
    data = yaml.load(fp)
    #print type(data)
for elem in data:
    print type(elem)
    print elem['spec']
#yaml.dump(data, sys.stdout)
```

**This is a small python program just to read a yaml file. It throws the same error.**

> Traceback (most recent call last):
  File "k8s_automate.py", line 12, in <module>
    print elem['spec']
TypeError: string indices must be integers, not str

I am still facing this issue, please help with this.

**Comment by rallytime** [comment]
@prokashyap The 2014.7.0 and 2014.7.1 releases are no longer maintained. Can you file a new issue with all of the information about the trouble you're facing and the versions you're using?
