### ISSUE TITLE
unicode on ec2 cloud

### ISSUE THREAD

**Issue by neezgee** [saltstack/salt#20823]
Hello! EC2 operations fails when there is unicode tags on any of instances:

```
$ salt-call -l trace cloud.full_query
.....
[DEBUG   ] Failed to execute 'ec2.list_nodes_min()' while querying for running nodes: 'ascii' codec can't encode characters in position 70860-70863: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2198, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2720, in list_nodes_min
    instances = query(params)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 345, in query
    result.text
UnicodeEncodeError: 'ascii' codec can't encode characters in position 70860-70863: ordinal not in range(128)
......
```

By the way, even with --hard-crash option this exception is caught somewhere, and I can't figure out how to run pdb to debug it.

**Comment by techhat** [comment]
@neezgee, can you paste the output of `salt-cloud --versions-report` please? I've come across this error sometimes when using requests, which is no longer the default in the 2015.2 and develop branches.

**Comment by neezgee** [comment]
Salt: 2014.7.1
          Python: 2.7.3 (default, Mar 14 2014, 11:57:14)
          Jinja2: 2.6
        M2Crypto: 0.21.1
  msgpack-python: 0.1.10
    msgpack-pure: Not Installed
        pycrypto: 2.6
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 13.1.0
            RAET: Not Installed
             ZMQ: 3.2.3
            Mako: 0.7.0
 Apache Libcloud: 0.17.0

Sorry, I did not tested on development.

**Comment by rallytime** [comment]
@neezgee That's ok! Are you in a position to give the newer branch like 2015.2 a try to see if this is fixed? No worries if not as we can try to reproduce your error and see if it is fixed in a newer branch.

**Comment by neezgee** [comment]
This is on development:

# salt-call -l trace cloud.full_query

...
[DEBUG   ] "GET /?Action=DescribeInstances&Version=2014-10-01 HTTP/1.1" 200 None
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] Failed to execute 'ec2.list_nodes_min()' while querying for running nodes: 'ascii' codec can't encode characters in position 181503-181506: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2236, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2986, in list_nodes_min
    sigver='4')
  File "/usr/lib/python2.7/site-packages/salt/utils/aws.py", line 367, in query
    result.text
UnicodeEncodeError: 'ascii' codec can't encode characters in position 181503-181506: ordinal not in range(128)

....

# salt-cloud --versions-report
            Salt: 2015.2.0rc1-2225-ga0440c6
          Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.4
            Mako: Not Installed
 Apache Libcloud: Not Installed

As with 2014.7, even with --hard-crash there is no clean message what is going on. Command just return empty result.

**Comment by danielgblanco** [comment]
Hi there,

I'm facing the same problem here when trying to create an instance:

```
[DEBUG   ] EC2 Request: https://ec2.us-east-1.amazonaws.com/
[WARNING ] /usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL c
onnections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[DEBUG   ] EC2 Response Status Code: 200
[DEBUG   ] Failed to execute 'ec2.list_nodes_min()' while querying for running nodes: 'ascii' codec can't encode character u'\ufffd' in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2198, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2720, in list_nodes_min
    instances = query(params)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 345, in query
    result.text
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 1: ordinal not in range(128)
[DEBUG   ] LazyLoaded .returner
local:
    False
```
These are versions I'm running
```
[root@skipjaq-salt-master2 ~]# salt-cloud --versions-report
            Salt: 2014.7.1
          Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
          Jinja2: 2.7.2
        M2Crypto: 0.21.1
  msgpack-python: 0.4.4
    msgpack-pure: Not Installed
        pycrypto: 2.6.1
         libnacl: Not Installed
          PyYAML: 3.10
           ioflo: Not Installed
           PyZMQ: 14.3.1
            RAET: Not Installed
             ZMQ: 3.2.5
            Mako: Not Installed
 Apache Libcloud: Not Installed
```
Also, I just upgraded requests to 2.6.1

**Comment by danielgblanco** [comment]
After downgrading requests to 2.5.3 the problem is solved :)

**Comment by techhat** [comment]
@danielgblanco, interesting. Would you consider this an upstream issue in requests then?

**Comment by mspinassi** [comment]
Just hitted by this bug.

We had an instance with a TAG with an 'á' character.

Here is my salt-cloud version (latest version at an amazon ami):

```
# salt-cloud --version
salt-cloud 2014.7.5 (Helium)
```

**Comment by vutny** [comment]
This is still an issue in version `2016.11.8`.
If any AWS EC2 instance has a tag value with a unicode (UTF-8) symbol in it, and caching is enabled in Salt Cloud config file:
```yaml
update_cachedir: True
```
The result of running `salt-cloud -l debug -F` is the following:
```
[DEBUG   ] Using AWS endpoint: ec2.us-east-1.amazonaws.com
[DEBUG   ] AWS Request: https://ec2.us-east-1.amazonaws.com/?Action=DescribeInstances&Version=2014-10-01
[DEBUG   ] AWS Response Status Code: 200
[DEBUG   ] LazyLoaded cloud.cache_node_list
[WARNING ] /usr/lib/python2.7/site-packages/salt/utils/cloud.py:3003: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  diff = cmp(new_data, cache_data)

[DEBUG   ] Failed to execute 'ec2.list_nodes_full()' while querying for running nodes: 'ascii' codec can't decode byte 0xe2 in position 39: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2395, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3345, in list_nodes_full
    ret.update(_list_nodes_full(loc))
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 3444, in _list_nodes_full
    __utils__['cloud.cache_node_list'](ret, provider, __opts__)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2892, in cache_node_list
    diff_node_cache(prov_dir, node, nodes[node], opts)
  File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 3003, in diff_node_cache
    diff = cmp(new_data, cache_data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 39: ordinal not in range(128)
```

Versions report:
```
Salt Version:
            Salt: 2016.11.8
 
Dependency Versions:
 Apache Libcloud: 0.20.1
            cffi: 0.8.6
        cherrypy: 5.6.0
        dateutil: 1.5
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.7.2
         libgit2: 0.21.0
         libnacl: Not Installed
        M2Crypto: 0.21.1
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: 0.21.4
          Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
    python-gnupg: 0.3.8
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 ```

**Comment by vutny** [comment]
Fixed by #45459. FYI @rallytime
