### ISSUE TITLE
VMWare Salt-Cloud documentation is missing since Website has been updated

### ISSUE THREAD

**Issue by CedNantes** [saltstack/salt#23856]
The VMWare docs are missing. I can still reach part of it with regular url like :
http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vsphere.html

but it's not anymore on the summary.

**Comment by nmadhok** [comment]
@rallytime Confirmed the issue! The docs cannot be found at http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html
or
http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html

**Comment by jacobhammons** [comment]
This is fixed in the develop branch, it won't show up in the current docs though since that is tracking 2015.5 (vmware cloud doesn't seem to be in that branch). @CedNantes @nmadhok

**Comment by rallytime** [comment]
@jacobhammons That's correct. The new VMWare cloud driver is new to the develop branch.

**Comment by nmadhok** [comment]
@jacobhammons Shouldn't http://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.vmware.html point to http://docs.saltstack.com/en/develop/ref/clouds/all/salt.cloud.clouds.vmware.html or in other words latest point to develop?

**Comment by jacobhammons** [comment]
@nmadhok with the update, 'latest' now points to the latest stable release, and we added a new folder for develop. This is a change from previous behavior but we thought it made more sense this way.

Regarding the search, I've set up a separate search instance for each folder, so when you search in 'develop' you'll only see results for develop. Right now it doesn't seem that google has picked up the new vmware file after I added it, I'll see if I can figure out how to trigger a reindex.

**Comment by nmadhok** [comment]
@jacobhammons salt.cloud.clouds.vmware still does not appear under the search on develop. Only Getting Started with VMware does.

**Comment by jacobhammons** [comment]
@nmadhok looks like this is being indexed now, not sure why it took so long for the google search index to find it.

**Comment by nmadhok** [comment]
@jacobhammons Closing this issue since this has been resolved.
