### ISSUE TITLE
Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#26934]
Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.

Docker version: 1.7.0-dev, build 5e06332
docker-py     - Python client for Docker.
  INSTALLED: 1.3.1 (latest)
salt 2015.8.0-262-gc34c6b9 (Beryllium)

**Comment by jfindlay** [comment]
@jagguli, thanks for the report.  Is it possible for you to post the associated minion log and stack trace?

**Comment by mbartsch** [comment]
I have the same issue.

minion log:
2015-12-12 16:10:26,022 [salt.state       ][ERROR   ][6891] Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
2015-12-12 16:10:26,055 [salt.loaded.int.states.dockerng][ERROR   ][6891] Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 1520, in running
    changes_needed = _compare(pre_config, create_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 150, in _compare
    _api_mismatch(item)
  File "/usr/lib/python2.7/site-packages/salt/states/dockerng.py", line 99, in _api_mismatch
    'be due to a change in the Docker API'.format(param)

2015-12-12 16:10:26,056 [salt.state       ][ERROR   ][6891] Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.

**Comment by Arabus** [comment]
Just ran into the same issue when trying to build a rabbitmq container from scratch:

```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.22
           Mako: 1.0.3
         PyYAML: 3.11
          PyZMQ: 15.1.0
         Python: 2.7.11 (default, Jan  4 2016, 23:48:42)
           RAET: 0.6.3
        Tornado: 4.3
            ZMQ: 4.1.2
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.2.1
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.7
          smmap: Not Installed
        timelib: 0.2.4
 
System Versions:
           dist: gentoo 2.2 
        machine: x86_64
        release: 4.1.7-hardened-r1
         system: Gentoo Base System 2.2 
```

Statefiles:
```
rabbitmq - server image:
  dockerng.image_present:
    - name: 'rabbitmq-server'
    - build: '/srv/salt/files/dockerfiles/rabbitmq'
rabbitmq - message broker:
  dockerng.running:
    - name: 'ye_olde_postman'
    - image: 'rabbitmq-server'
    - domainname: 'feileacan.de'
    - restart_policy: 'on-failure:5'
    - ports:
      - '5671'
      - '15672'
    - memory: '2G'
    - watch:
      - dockerng: 'rabbitmq - server image' 
```

Messages from error log:
```
00:15:25,867 [salt.state       ][INFO    ][16294] Running state [ye_olde_postman] at time 00:15:25.866905
00:15:25,867 [salt.state       ][INFO    ][16294] Executing state dockerng.running for ye_olde_postman
00:15:25,883 [salt.loaded.int.states.dockerng][ERROR   ][16294] Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib64/python2.7/site-packages/salt/states/dockerng.py", line 1520, in running
    changes_needed = _compare(pre_config, create_kwargs)
  File "/usr/lib64/python2.7/site-packages/salt/states/dockerng.py", line 150, in _compare
    _api_mismatch(item)
  File "/usr/lib64/python2.7/site-packages/salt/states/dockerng.py", line 99, in _api_mismatch
    'be due to a change in the Docker API'.format(param)

00:15:25,883 [salt.state       ][ERROR   ][16294] Uncaught exception "Unable to compare configuration for the 'memory' parameter. This may be due to a change in the Docker API" encountered while comparing existing container against desired configuration. See minion log for exception info.
00:15:25,884 [salt.state       ][INFO    ][16294] Completed state [ye_olde_postman] at time 00:15:25.883602
```

Docker info
```
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:4-13780447-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Metadata Space Used: 10.86 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.1.7-hardened-r1
Operating System: Gentoo/Linux
```

I'm using docker-py v1.5.0

**Comment by Arabus** [comment]
Found the issue cause. It is as the error message says, the docker api has changed. Unfortunately the salt dockerng module has hardcoded values, where in the dict of a docker container a certain member of VALID_CREATE_OPTS should be. 

In this case my `/usr/lib64/python2.7/site-packages/salt/modules/dockerng.py` contains:
```
...
    'memory': {                                                                                                        
        'api_name': 'mem_limit',                                                                                       
        'path': 'Config:Memory',                                                                                       
        'default': 0,                                                                                                  
    },
...
```
The `_compare` function in `/usr/lib64/python2.7/site-packages/salt/states/dockerng.py` then tries this:
```
    _get = lambda path: (
        salt.utils.traverse_dict(actual, path, NOTSET, delimiter=':')
    )
    ret = {}
    for item, data, in six.iteritems(create_kwargs):
        if item not in VALID_CREATE_OPTS:
            log.error(
                'Trying to compare \'{0}\', but it is not a valid '
                'parameter. Skipping.'.format(item)
            )
            continue
        log.trace('dockerng.running: comparing ' + item)
        conf_path = VALID_CREATE_OPTS[item]['path']
        if isinstance(conf_path, tuple):
            actual_data = [_get(x) for x in conf_path]
            for val in actual_data:
                if val is NOTSET:
                    _api_mismatch(item)
        else:
            actual_data = _get(conf_path)
            if actual_data is NOTSET:
                _api_mismatch(item)
```

This would have worked until docker API [v1.17](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.17/#inspect-a-container), in[v1.18](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#inspect-a-container) they switched to the HostConfig subdict and are no longer accessible at `Config:$PARAM`

This sounds awfully familiar to #27265 where i already mentioned that this format is deprecated.

I guess either one now has to store different values in the VALID_CREATE_OPTS depending on the docker API present oder version them or get rid of that part entirely.

**Comment by ticosax** [comment]
has been fixed by #31326

**Comment by rallytime** [comment]
@jagguli or @Arabus are either of you in a position to give that fix a try and confirm this is fixed? If not, the fix will be available in the upcoming 2015.8.8 release.

**Comment by Arabus** [comment]
I'd like to but unfortunately the saltstack:2015.8 branch does not yield a running salt-master for me. I have been trying to follow the guide for https://docs.saltstack.com/en/latest/topics/development/hacking.html but to no avail. I can give it another go on Sunday though.

**Comment by cachedout** [comment]
@Arabus Were you able to try this?

**Comment by Arabus** [comment]
Unfortunately I still have Problems setting up a proper dev environment and am currently swamped with work so I will most likely not be able to test this until the easter holidays.

**Comment by rallytime** [comment]
I am going to close this as fixed by #31326. If people bump into this again, please leave a comment an we'll be happy to take another look.
