### ISSUE TITLE
PID check failed. RNG must be re-initialized after fork()

### ISSUE THREAD

**Issue by kitplummer** [saltstack/salt#27690]
When provisioning a Windows server in AWS Im getting this:

```
TRACE: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 55, in _call
    ret = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2182, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1241, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 2267, in create
    vm_, data, ip_address, display_ssh_output
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 1992, in wait_for_instance
    call='action',
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/ec2.py", line 4021, in get_password_data
    sentinel = Crypto.Random.new().read(15 + dsize)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    ra
```

Seeing this on CentOS7 with version: salt-cloud 2015.5.5 (Lithium)

**Comment by kitplummer** [comment]
```
[root@ip-*** srv]# salt --versions-report
           Salt: 2015.5.5
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
```

**Comment by jfindlay** [comment]
@kitplummer, thanks for the report.

**Comment by rallytime** [comment]
@kitplummer Can you also post your **sanitized** cloud provider and profile configs?

**Comment by kitplummer** [comment]
Sure thing.

Provider:

```
us-east-1-private-ips:
  provider: ec2
  minion:
    master: ***
    mine_functions:
      network.interfaces: []
      network.ip_addrs: []
      test.ping: []
      grains.items: []
    mine_interval: 2
 # ip address salt-cloud should connect to
  ssh_interface: public_ips
  # aws credentials
  id: ***
  key: '***'
  # ssh key
  keyname: salt
  private_key: /etc/salt/***.pem
  # aws location
  location: us-east-1
  availability_zone: us-east-1d
  # aws security group
  securitygroup: default
  # delete aws root volume when minion is destroyed
  del_root_vol_on_destroy: True
  # local user
  ssh_username: root
  # rename on destroy
  rename_on_destroy: True
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True

  # Optionally configure the Windows credential validation number of
  # retries and delay between retries.  This defaults to 10 retries
  # with a one second delay betwee retries
  win_deploy_auth_retries: 10
  win_deploy_auth_retry_delay: 1
```

Profile:

```
windows.t2.medium.us-east:
  provider: us-east-1-private-ips
  image: ami-***
  size: t2.medium
  del_root_vol_on_destroy: True
  win_username: Administrator
  win_password: auto
  userdata_file: /etc/salt/windows-firewall.ps1
  win_installer: /etc/salt/Salt-Minion-2015.5.5-AMD64-Setup.exe
```

**Comment by kitplummer** [comment]
I don't see this error with 2015.8.1 - so I'm guessing something was resolved.  It may have been my install of winexe or even impacket.

**Comment by rallytime** [comment]
@kitplummer Glad you got it working! If it pops up again let us know and we can take another look.

**Comment by themalkolm** [comment]
I'm getting this error in `2015.8.1` while trying to `cloud.create` an instance using `saltify`. It fails to run under reactor but runs OK if I do it manually via cli. So I guess forking is still broken.

```
salt_master:
    ----------
    _stamp:
        2015-11-02T17:34:33.326403
    fun:
        runner.cloud.create
    jid:
        20151102173433023549
    return:
        Exception occurred in runner cloud.create: Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 337, in low
            data['return'] = self.functions[fun](*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/salt/runners/cloud.py", line 160, in create
            info = client.create(provider, instances, **create_kwargs)
          File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 401, in create
            mapper.create(vm_))
          File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1189, in create
            self.opts
          File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 159, in gen_keys
            salt.crypt.gen_keys(tdir, 'minion', keysize)
          File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 88, in gen_keys
            gen = RSA.generate(bits=keysize, e=65537)
          File "/usr/lib64/python2.7/site-packages/Crypto/PublicKey/RSA.py", line 508, in generate
            obj = _RSA.generate_py(bits, rf, progress_func, e)    # TODO: Don't use legacy _RSA module
          File "/usr/lib64/python2.7/site-packages/Crypto/PublicKey/_RSA.py", line 50, in generate_py
            p = pubkey.getStrongPrime(bits>>1, obj.e, 1e-12, randfunc)
          File "/usr/lib64/python2.7/site-packages/Crypto/Util/number.py", line 265, in getStrongPrime
            randfunc)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
            return self._singleton.read(bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
            return _UserFriendlyRNG.read(self, bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 132, in read
            retval = self._fa.random_data(N)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 148, in random_data
            return self.generator.pseudo_random_data(bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 93, in pseudo_random_data
            for i in xrange(num_full_blocks):
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
            return self._singleton.read(bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
            return _UserFriendlyRNG.read(self, bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 132, in read
            retval = self._fa.random_data(N)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 148, in random_data
            return self.generator.pseudo_random_data(bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 93, in pseudo_random_data
            for i in xrange(num_full_blocks):
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
            return self._singleton.read(bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
            return _UserFriendlyRNG.read(self, bytes)
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
            self._check_pid()
          File "/usr/lib64/python2.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
            raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
        AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
    success:
        False
    user:
        Reactor
```
