### ISSUE TITLE
Salt 2015.5.3 - Could not deserialize msgpack message error.

### ISSUE THREAD

**Issue by my10c** [saltstack/salt#29991]
Trying to copy a 13mb tgz file across all minions and failed 
deleted the directory mention above, restarted the master and all minions : from #25581

```
 salt-cp "*" my.tgz /tmp/my.tgz
```

Error:

```
CRITICAL] Could not deserialize msgpack message: Unexpected Error in MworkerThis often happens when trying to read a file not in binary mode.Please open an issue and include the following error: unpack(b) recieved extra data.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
SaltClientError: unpack(b) recieved extra data.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 203, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 47, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 114, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 531, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 286, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: unpack(b) recieved extra data.
```

```
salt --versions-report
                  Salt: 2015.5.3
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
               Tornado: Not Installed
 Debian source package: 2015.5.3+ds-1trusty1
```

All minions show the same versions-report

Any idea? It a huge issue...

thanks

**Comment by lsuryo** [comment]
more test 
dd if=/dev/zero of=test_file bs=1024 count=1024
salt-cp "*" test_file.gz /tmp/test_file.gz

works : so its an size issue!'

**Comment by lsuryo** [comment]
salt '*' -t 2400 -b 1 cp.get_file salt://files/my_file.tgz /tmp/my_file.tgz
partial works, so not useful

So I end up using pssh to solve this time.. but it would  be nice if salt can do this...

**Comment by jfindlay** [comment]
@lsuryo, thanks for the report.  I think this issue has been fixed in more recent versions of salt.  Are you able to try 2015.8.3?

**Comment by lsuryo** [comment]
I need to stick with current version (2015.5.3 for now) in production. I'l do some testing in the none-production env sometime end of next month, and will report back. Happy New year!

**Comment by cachedout** [comment]
@lsuryo Were you ever able to get back to this? 

@Ch3LL Perhaps you could try to reproduce this on 2016.3?

**Comment by lsuryo** [comment]
upgrade is plan for next week, I will then test the issue/fix against the newer version of salt (2016-03)

**Comment by lsuryo** [comment]
decided to upgrade since we need this fix sooner then later: it still failed with 2016-03

``
dd if=/dev/zero of=salt-data.test bs=10240 count=10000

salt-cp  '*' ./salt-data.test /tmp/

[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 321, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 38, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 105, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 558, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 313, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt-cp", line 10, in <module>
    salt_cp()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 321, in salt_cp
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 38, in run
    cp_.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/cp.py", line 105, in run
    ret = local.cmd(*args)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 558, in cmd
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 313, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
``

``
 salt --versions-report                                                                                  2
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-87-generic
         system: Linux
        version: Ubuntu 14.04 trusty
``
