### ISSUE TITLE
salt pkg.refresh_db on W2012R2 throws exception

### ISSUE THREAD

**Issue by arg0nik** [saltstack/salt#32622]
I'm trying to run pkg.refresh_db on W2012R2 from my master after having installed GitPython on my master and Git on Windows in my test cluster using 'sudo salt <target> pkg.refresh_db.' This is a fairly vanilla setup, I haven't changed the roots directory (at /srv/salt). This is my result:

```

    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 391, in refresh_db
        genrepo(saltenv=saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 437, in genrepo
        __opts__['renderer'])
      File "c:\salt\bin\lib\site-packages\salt\template.py", line 95, in compile_template
        ret = render(input_data, saltenv, sls, **render_kwargs)
      File "c:\salt\bin\lib\site-packages\salt\renderers\yaml.py", line 51, in render
        data = load(yaml_data, Loader=get_yaml_loader(argline))
      File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 71, in load
        return loader.get_single_data()
      File "c:\salt\bin\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
        node = self.get_single_node()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 36, in get_single_node
        document = self.compose_document()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 98, in check_event
        self.current_event = self.state()
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
        "expected <block end>, but found %r" % token.id, token.start_mark)
    ParserError: while parsing a block mapping
      in "<unicode string>", line 3, column 5:
            full_name: 'ESET Endpoint Antivirus'
            ^
    expected <block end>, but found '<scalar>'
      in "<unicode string>", line 8, column 21:
            install_flags: '/qn ALLUSERS=1 /norestart'
```

Master:

```
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.2
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Red Hat Enterprise Linux Server 7.2 Maipo
```

Minion:

```
    Salt Version:
               Salt: 2015.8.7

    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed

    System Versions:
               dist:
            machine: AMD64
            release: 2012ServerR2
             system: 2012ServerR2 6.3.9600  Multiprocessor Free

```

**Comment by jfindlay** [comment]
@greenage, thanks for reporting.

**Comment by cachedout** [comment]
Were you using this repo? https://github.com/saltstack/salt-winrepo-ng/blob/01b2d49d9bc3c8b6487503336b7de5088cc8c568/eea.sls

I'll bet this bug was fixed here: https://github.com/saltstack/salt-winrepo-ng/commit/d4be311f18a98086c8ef8b905231c93fa332e028#diff-a4296b61730e2e7e71d1ffbdf0644457

**Comment by greenage** [comment]
That is likely, I pulled down the repos using winrepo.update_git_repos. I just tried to run it again and got the same output.

salt <target> winrepo.update_git_repos
   ```
https://github.com/saltstack/salt-winrepo-ng.git:
        True
    https://github.com/saltstack/salt-winrepo.git:
        True

```
Then ran the refresh_db command with the same error.

I checked the contents from the file at /srv/salt/win/repo-ng/salt-winrepo-ng/eea.sls and noted that the single quote was still missing despite having run the update command. I tried adding it and ran the command. I now get a different error:

```
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 391, in refresh_db
        genrepo(saltenv=saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 437, in genrepo
        __opts__['renderer'])
      File "c:\salt\bin\lib\site-packages\salt\template.py", line 95, in compile_template
        ret = render(input_data, saltenv, sls, **render_kwargs)
      File "c:\salt\bin\lib\site-packages\salt\renderers\yaml.py", line 51, in render
        data = load(yaml_data, Loader=get_yaml_loader(argline))
      File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 71, in load
        return loader.get_single_data()
      File "c:\salt\bin\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
        node = self.get_single_node()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 36, in get_single_node
        document = self.compose_document()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 98, in check_event
        self.current_event = self.state()
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
        "expected <block end>, but found %r" % token.id, token.start_mark)
    ParserError: while parsing a block mapping
      in "<unicode string>", line 4, column 2:
         '2.3.10':
         ^
    expected <block end>, but found '<block mapping start>'
      in "<unicode string>", line 15, column 3:
          '2.3.8':

```

**Comment by twangboy** [comment]
@greenage 
Above you said you ran `salt winrepo.update_git_repos`. That command should have failed. The correct command is `salt-run winrepo.update_git_repos`. 

In case that was a typo and you actually did use the `salt-run` command, let's try clearing the repo on your master and re-running the `update_git_repos` commnad. On your master, could you do the following:
1. Remove the directory named `salt-winrepo-ng` from the `/srv/salt/win/repo-ng/` directory
2. Run `salt-run winrepo.update_git_repos`
3. Run `salt '<windows minion name>' pkg.refresh_db`

Please post your results.

**Comment by greenage** [comment]
You were right I had used the incorrect command. I tried it again using salt-run without result. Then, following your instruction I did the following on the master:

1. `rm -rf /srv/salt/win/repo-ng/salt-winrepo-ng/` 
2. `salt-run winrepo.update_git_repos`:
Result:
```
https://github.com/saltstack/salt-winrepo-ng.git:
    /srv/salt/win/repo-ng/salt-winrepo-ng
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo
```

3. `salt 'windows_minion' pkg.refresh_db`, which gave a similar result as before:
```
sudo salt 'WindowsMinion*' pkg.refresh_db

    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1071, in _thread_return
        return_data = func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 391, in refresh_db
        genrepo(saltenv=saltenv)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 437, in genrepo
        __opts__['renderer'])
      File "c:\salt\bin\lib\site-packages\salt\template.py", line 95, in compile_template
        ret = render(input_data, saltenv, sls, **render_kwargs)
      File "c:\salt\bin\lib\site-packages\salt\renderers\yaml.py", line 51, in render
        data = load(yaml_data, Loader=get_yaml_loader(argline))
      File "c:\salt\bin\lib\site-packages\yaml\__init__.py", line 71, in load
        return loader.get_single_data()
      File "c:\salt\bin\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
        node = self.get_single_node()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 36, in get_single_node
        document = self.compose_document()
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 55, in compose_document
        node = self.compose_node(None, None)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 84, in compose_node
        node = self.compose_mapping_node(anchor)
      File "c:\salt\bin\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
        while not self.check_event(MappingEndEvent):
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 98, in check_event
        self.current_event = self.state()
      File "c:\salt\bin\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
        "expected <block end>, but found %r" % token.id, token.start_mark)
    ParserError: while parsing a block mapping
      in "<unicode string>", line 3, column 5:
            full_name: 'ESET Endpoint Antivirus'
            ^
    expected <block end>, but found '<scalar>'
      in "<unicode string>", line 8, column 21:
            install_flags: '/qn ALLUSERS=1 /norestart'
                            ^

Output of /srv/salt/win/repo-ng/salt-winrepo-ng/eea.sls: 
```



eea:
  '6.3.2016.0':
    full_name: 'ESET Endpoint Antivirus'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'http://download.eset.com/download/win/eea/eea_nt64_enu.msi'
    uninstaller: 'http://download.eset.com/download/win/eea/eea_nt64_enu.msi'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'http://download.eset.com/download/win/eea/eea_nt32_enu.msi'
    uninstaller: 'http://download.eset.com/download/win/eea/eea_nt32_enu.msi'
    {% endif %}
    install_flags: '/qn ALLUSERS=1 /norestart'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  '6.2.2021.0':
    full_name: 'ESET Endpoint Antivirus'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'salt://win/repo-ng/eea/v6/eea_nt64_enu.msi'
    uninstaller: 'salt://win/repo-ng/eea/v6/eea_nt64_enu.msi'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'salt://win/repo-ng/eea/v6/eea_nt32_enu.msi'
    uninstaller: 'salt://win/repo-ng/eea/v6/eea_nt32_enu.msi'
    {% endif %}
    install_flags: '/qn ALLUSERS=1 /norestart'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  '5.0.2254.0':
    full_name: 'ESET Endpoint Antivirus'
    {% if grains['cpuarch'] == 'AMD64' %}
    installer: 'salt://win/repo-ng/eea/v5/eea_nt64_enu.msi'
    uninstaller: 'salt://win/repo-ng/eea/v5/eea_nt64_enu.msi'
    {% elif grains['cpuarch'] == 'x86' %}
    installer: 'salt://win/repo-ng/eea/v5/eea_nt32_enu.msi'
    uninstaller: 'salt://win/repo-ng/eea/v5/eea_nt32_enu.msi'
    {% endif %}
    install_flags: '/qn ALLUSERS=1 /norestart'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False


```
