### ISSUE TITLE
Non-informative "Too many functions declared in state 'file' in SLS"

### ISSUE THREAD

**Issue by non7top** [saltstack/salt#38098]
This error message is non-informative at all. At very least it should report the ID where the issue happens and preferably the line in the file.

**Comment by Ch3LL** [comment]
@non7top can you explain how you are running into this specifically? Possibly a reproducable case?

I'm just wondering if there is more information in the debug output as well. Thanks

**Comment by non7top** [comment]
The offending snippet was like this which took me a while to identify. vim syntax highlighting helped as it colored - salt:// in white while normally attributes(or whatever it is) are cyan.
Obviously salt should have reported something like "ID /etc/file has errors: Too many functions declared in state: managed and salt:// can't be used together". 
```
/etc/file:
  file.managed:
    - template: jinja
    - salt://webserver/files/etc_file
    - require_in:
```

**Comment by shallot** [comment]
I had a similar run-in with this error message, and it was caused by doing this:

```
apt-get update and upgrade:
  pkg.uptodate:
    - refresh
```

rather than this:

```
apt-get update and upgrade:
  pkg.uptodate:
    - refresh: True
```

This seems eminently detectable - surely the error handler can spell out *which* 'function' was extra, and point the user more clearly to the problem. For example, say "Too many functions declared in state X in Y: please choose between 'uptodate' and 'refresh'."

Indeed, it could then also try to cross-reference the list of extra functions with the list of valid arguments to the state used, and pinpoint the error even more clearly. For example, "Too many functions declared in state X in Y: unknown function detected: 'refresh' - did you mean the boolean parameter to function uptodate?"

**Comment by Ch3LL** [comment]
Agreed I'll label this as a bug that we will need to get fixed up thanks :) Thanks for the particular examples that will help.

**Comment by ngeovanis** [comment]
I ran into this error message on a simple state shown below. The proximate cause turned-out to be using this: 
    - mode:770
...instead of this:
    - mode: 770
IOW lack of " " between ":" and "7".

ossec-tar-file:
  file.managed:
{% if grains['os'] == 'Debian' %}
    - name: '/var/ossec/ossec-hids-agent_2.9.2.2154stretch_amd64.deb'
    - source:
      - salt://ossec/files/ossec-hids-agent_2.9.2.2154stretch_amd64.deb
{% elif grains['os'] == 'Ubuntu' %}
    - name: '/var/ossec/ossec-hids-agent_2.9.2-2154xenial_amd64.deb'
    - source:
      - salt://ossec/files/ossec-hids-agent_2.9.2-2154xenial_amd64.deb
{% endif %}    
    - user: root
    - group: ossec
    - mode: 770

**Comment by ngeovanis** [comment]
FYI my indenting has been lost in the state quoted above.....

**Comment by marco-m** [comment]
Hello any news ?

**Comment by Ch3LL** [comment]
@marco-m no one is currently working on this issue due to other higher priority issues. Please feel free to take a stab at a fix for this particular use case

**Comment by ngeovanis** [comment]
As I mentioned on 10 November, my specific problem was fixed with a 1-character change: An additional space between the colon and the keyword, eg. "Mode: 770" instead of "Mode:770".

**Comment by emerichunter** [comment]
Hi, 
I had the same message today for a similar problem. I was missing a space 'maker_start:"<whatever>"'  instead of 'maker_start: "<whatever>"'. This would be a nice addon. Glad I found this issue BTW, it was really helpfull.

**Comment by DimentR** [comment]
If after **mode:** not write space, appears this error.

**Comment by srkunze** [comment]
I found this issue being reproduced by this:

```
{{ system.name}}__directories__absent:
  file.absent:
    - {{ system.home }}/attachments
    - require:
      - home_directory__{{ system.home }}
    - require_in:
      - {{ system.name }}__virtualenv
```

Fix:
```
{{ system.name}}__directories__absent:
  file.absent:
    - name: {{ system.home }}/attachments
    - require:
      - home_directory__{{ system.home }}
    - require_in:
      - {{ system.name }}__virtualenv
```

**Comment by udf2457** [comment]
Bit depressing to see this bug still exists five years later.  Its the world's most useless error message.

**Comment by Freddyp91** [comment]
Currently having this issue..looking through config trying to find which line it could be.

**Comment by Freddyp91** [comment]
Going to the minion and 'tail -f /var/log/minion ' helped me to determine what the issue was..It wasn't spaces at all for me but that i had forgot to add a file that file.managed was pointing to..

**Comment by theYaric** [comment]
Also got this error due to missing space.

    - repl:'#\1'

 This is pathetic. First, inability to implement RE parsing. Second, misleading error message. Even 'Something wrong. Error #123456' will be more beneficial to user.  And the last, this shameful error exists for 6 years now. 

I am speechless.

**Comment by whytewolf** [comment]
this should be fixed with the merge of #65212
