### ISSUE TITLE
No Top file or external nodes data matches found

### ISSUE THREAD

**Issue by ccrivelli** [saltstack/salt#38719]
### Description of Issue/Question
Top file not found:
```
minion.internal:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for minion.internal
------------
Succeeded: 0
Failed:    1
------------
```

### Setup
```
# cat /etc/salt/master.d/file_roots.conf 
file_roots:
  mgmt:
    - /srv/salt/mgmt/states/
  dev:
    - /srv/salt/dev/states/
  stage:
    - /srv/salt/stage/states/
  prod:
    - /srv/salt/prod/states/
```
-- only 1 top file in 'mgmt' env:
```
# ls /srv/salt/mgmt/states/top.sls 
/srv/salt/mgmt/states/top.sls
```

### Steps to Reproduce Issue
-- upgrade the saltstack components from 2016.3.1-1 to 2016.11.1 (same behaviour with 2016.11.0) and run:
```
# salt '*' state.highstate
```

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
 
```
-- all saltstack components running with the same version
```
# rpm -qa | grep salt
salt-master-2016.11.1-1.el7.noarch
salt-2016.11.1-1.el7.noarch
salt-minion-2016.11.1-1.el7.noarch
salt-cloud-2016.11.1-1.el7.noarch
```

**Comment by ccrivelli** [comment]
I guess it's related in some way with this: https://github.com/saltstack/salt/pull/36922

Do you have any idea/suggestion how to fix it?
I was wondering if there's a workaround in terms of salt-minion config.

Thanks

**Comment by gtmanfred** [comment]
That pr is in 2016.11, so you shouldn't have a problem with it since you are on 2016.11.1.

Can you provide your top file?  and anything that is not the default in the master and minion configs?

**Comment by ccrivelli** [comment]
The topfile.sls is like:
```
mgmt:
  '^(a|b|c|d|e|f).domain.internal$':
    - match: pcre
    - state1
    - state2
    - state3
  'b.domain.internal':
    - state4
    - state5

prod:
  'prod*.domain.internal':
    - stateA
    - stateB

etc..
```

Yesterday I downgraded back to 2016.3.1-1  (master, minions) and everything is working again.
I kept only one minion with 2016.11.1 (so *only for this minion* the version of salt-master salt-minion  is different) and I'm having the same error here.

My current salt-master config differs from the default one only for these files (added):

```
# tree master.d/
master.d/
├── file_roots.conf
├── pillar_roots.conf
└── reactor.conf
```

Details:
```
# cat master.d/file_roots.conf 
file_roots:
  mgmt:
    - /srv/salt/mgmt/states/
  dev:
    - /srv/salt/dev/states/
  stage:
    - /srv/salt/stage/states/
  prod:
    - /srv/salt/prod/states/

--

# cat master.d/pillar_roots.conf 
pillar_roots:
  mgmt:
    - /srv/salt/mgmt/pillar/
  dev:
    - /srv/salt/dev/pillar/
  stage:
    - /srv/salt/stage/pillar/
  prod:
    - /srv/salt/prod/pillar/

--

# cat master.d/reactor.conf 

state_output: changes

reactor:
   - 'salt/beacon/*/inotify/something':        
      - /srv/salt/dev/reactors/alert.sls
  
```

Salt minions config is exactly like default (only changed the name of saltmaster host).

**Comment by gtmanfred** [comment]
I am unable to replicate this issue.

```
[root@173211f04d85 /]# salt \* state.apply
test:
----------
          ID: /etc/test.txt
    Function: file.touch
      Result: True
     Comment: Created empty file /etc/test.txt
     Started: 00:15:08.917578
    Duration: 68.181 ms
     Changes:
              ----------
              new:
                  /etc/test.txt

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  68.181 ms
```

```
[root@173211f04d85 /]# tree /srv/salt
/srv/salt
|-- dev
|   |-- pillar
|   `-- states
|-- mgmt
|   |-- pillar
|   `-- states
|       |-- test.sls
|       `-- top.sls
|-- prod
|   |-- pillar
|   `-- states
`-- stage
    |-- pillar
    `-- states

12 directories, 2 files
```

```
[root@173211f04d85 /]# tail -c +0 /etc/salt/master.d/*.conf /etc/salt/minion.d/*.conf
==> /etc/salt/master.d/test.conf <==
file_roots:
  mgmt:
    - /srv/salt/mgmt/states/
  dev:
    - /srv/salt/dev/states/
  stage:
    - /srv/salt/stage/states/
  prod:
    - /srv/salt/prod/states/

pillar_roots:
  mgmt:
    - /srv/salt/mgmt/pillar/
  dev:
    - /srv/salt/dev/pillar/
  stage:
    - /srv/salt/stage/pillar/
  prod:
    - /srv/salt/prod/pillar/

state_output: changes

==> /etc/salt/minion.d/_schedule.conf <==
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}

==> /etc/salt/minion.d/test.conf <==
id: test
master: localhost
```

If you want to try the docker image, you can try `gtmanfred/issues:38719`.

Can you give me any more information or a simple way to replicate this error in a docker container?

Thanks,
Daniel

**Comment by ccrivelli** [comment]
I played a bit with your docker image trying to reproduce the issue.
So far I found this:

(with this top.sls is all good)
```
[root@24d981e60399 states]# cat top.sls
mgmt:
  '^(a|b|c|d|e|f).internal$':
    - match: pcre
    - something100
  'a.internal':
    - something200
  'test':
    - test

[root@24d981e60399 states]# salt '*' state.highstate
test:
----------
          ID: /etc/test.txt
    Function: file.touch
      Result: True
     Comment: Updated times on file /etc/test.txt
     Started: 06:02:11.187013
    Duration: 2.007 ms
     Changes:   
              ----------
              touched:
                  /etc/test.txt

Summary for test
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.007 ms
```

(this top.sls is generating the error)
```
[root@24d981e60399 states]# cat top.sls
mgmt:
  '^(a|b|c|d|e|f).internal$':
    - match: pcre
    - something100
  'a.internal':
    - something200
   'test':
    - test

[root@24d981e60399 states]# salt '*' state.highstate
test:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code

```

The difference between the two top files above is just one space before 'test' and it seems to be causing the issue.

**Comment by ccrivelli** [comment]
Also with this simple top file, I'm getting the same error:

```
# cat top.sls 
mgmt:
  'prod.*':
    - test
[root@74246e56dbee states]# salt '*' state.highstate
test:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

In this case because it's not able to find any minion with id prod.* 
Not sure if this is my case though.

**Comment by gtmanfred** [comment]
That is the expected behavior, it is not finding any states for the minion you have targeted.

And for the other one, that is not a valid yaml, because of the extra space, so I think we might just be throwing away the last match.

Are you sure that your minion where you are seeing this error is actually matching anything in the top.sls file?

**Comment by gtmanfred** [comment]
I believe what you are actually seeing here is that the targeted minion is not actually matched in the top file.

This error means that it A) couldn't find a top file or B) couldn't match the minion to any set of states in any of the top files it found.

**Comment by ccrivelli** [comment]
Yeah, I understand what you mean.
I tried something different now, might this be the real cause?

This is the topfile:
```
# cat mgmt/states/top.sls 
prod:
  'prod*':
    - prodstate

stage:
  'test*':
    - stagestate
```

The top file is in mgmt, then I have one state for prod env and one state for stage env:
```
# tree
.
|-- dev
|   |-- pillar
|   `-- states
|-- mgmt
|   |-- pillar
|   `-- states
|       `-- top.sls
|-- prod
|   |-- pillar
|   `-- states
|       `-- prodstate.sls
`-- stage
    |-- pillar
    `-- states
        `-- stagestate.sls
```

The minion id is 'test': 
```
# grep -R 'id:' /etc/salt/minion*
/etc/salt/minion:#id:
/etc/salt/minion.d/test.conf:id: test


# salt-key -L
Accepted Keys:
test
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```
..but there's no environment specified in the minion config (like my original config, it's commented):
```
# grep -R 'environment:' /etc/salt/minion*
/etc/salt/minion:#environment: None
```

I expect the 'stagestate' would be executed to match the 'test*' regexp, but I get the error:
```
test:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

I guess it's looking for the topfile in the wrong env even if the I'm targeting using the minion id.
What do you think?

I have the feeling we are close to the solution...

**Comment by gtmanfred** [comment]
I have replicated this error.  The image is still the same

```
[root@e15b9854278f /]# tree /srv/salt/
/srv/salt/
|-- dev
|   |-- pillar
|   `-- states
|-- mgmt
|   |-- pillar
|   `-- states
|       `-- top.sls
|-- prod
|   |-- pillar
|   `-- states
|       `-- test.sls
`-- stage
    |-- pillar
    `-- states

12 directories, 2 files
[root@e15b9854278f /]# tail -c +0 /srv/salt/*/states/*.sls
==> /srv/salt/mgmt/states/top.sls <==
prod:
  '*':
    - test

==> /srv/salt/prod/states/test.sls <==
/etc/test.txt:
  file.touch
[root@e15b9854278f /]# salt-call state.apply
local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

@terminalmage can you take a look at this?

Thanks,
Daniel

**Comment by terminalmage** [comment]
This is expected behavior. The default merging strategy was never intended to look at other environments' sections in a top file (e.g. looking for ``prod`` in the ``mgmt`` top file). This behavior was a bug, so for the 2016.11.0 release it was corrected, and a strategy called ``merge_all`` was added. Setting ``top_file_merging_strategy: merge_all`` in the minion configuration will use all sections from all top files when running a highstate.

**Comment by ccrivelli** [comment]
Still not working with ```top_file_merging_strategy: merge_all``` @terminalmage .
Details (replicating @gtmanfred config):
```
[root@16d4a3608eb5 ~]# tree /srv/salt/
/srv/salt/
|-- dev
|   |-- pillar
|   `-- states
|-- mgmt
|   |-- pillar
|   `-- states
|       `-- top.sls
|-- prod
|   |-- pillar
|   `-- states
|       `-- test.sls
`-- stage
    |-- pillar
    `-- states

12 directories, 2 files
[root@16d4a3608eb5 ~]# cat /srv/salt/mgmt/states/top.sls 
prod:
  '*':
    - test
```

Setting ```top_file_merging_strategy: merge_all``` in the minion configuration (minion restarted after):
```
[root@16d4a3608eb5 ~]# cat /etc/salt/minion.d/test.conf 
id: test
master: localhost
top_file_merging_strategy: merge_all
```

Same error:
```
[root@16d4a3608eb5 ~]# salt '*' state.highstate
test:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or external nodes data matches found.
     Changes:   

Summary for test
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

**Comment by ccrivelli** [comment]
When I started using salt, I read somewhere that the best practice was to manage only one topfile for all the environments.
Can you confirm that the default behaviour (and in this case I would say the best practice) is to handle one topfile per environment? 
If so, I might split my topfile in 4 different ones.

Thanks.

**Comment by gtmanfred** [comment]
You could do that, or you could set `state_top_saltenv: mgmt` or to whichever environment the top file is in.

I don't know why merge_all isn't working, but I verified that it is also not working for me in the docker image.

**Comment by ccrivelli** [comment]
Setting up ```state_top_saltenv: mgmt``` in the minion config doesn't work for me.
Same error.

I'm going to try splitting the topfile.

**Comment by terminalmage** [comment]
Assuming that you are still using this layout (copied from an earlier post):

```
# cat mgmt/states/top.sls 
prod:
  'prod*':
    - prodstate

stage:
  'test*':
    - stagestate

# tree
.
|-- dev
|   |-- pillar
|   `-- states
|-- mgmt
|   |-- pillar
|   `-- states
|       `-- top.sls
|-- prod
|   |-- pillar
|   `-- states
|       `-- prodstate.sls
`-- stage
    |-- pillar
    `-- states
        `-- stagestate.sls
```

My guess is that, since Salt is processing the ``mgmt`` environment's top file, it is looking in that environment for SLS files, instead of ``prod``. I'll need to dig deeper to confirm this though.

**Comment by terminalmage** [comment]
@gtmanfred I just tested using your image and was not able to reproduce using ``merge_all``.

However, I just realized that I mistakenly said to put the ``top_file_merging_strategy: merge_all`` in the minion config file, it should have been in the _master_ config file. I probably said this because in the testing I had been doing for an unrelated issue, I was using masterless salt (i.e. ``salt-call --local``), so all my fileserver/top file stuff was in the minion config file for that reason. Sorry for the confusion.

**Comment by terminalmage** [comment]
If you can both test using ``top_file_merging_strategy: merge_all`` in the _master_ config file instead of the minion config file, I think it should work for both of you.

**Comment by gtmanfred** [comment]
Yup, it works in the master config file.

Thanks,
Daniel

**Comment by terminalmage** [comment]
OK, @ccrivelli can you also confirm?

**Comment by ccrivelli** [comment]
Yes, I confirm that  using ```top_file_merging_strategy: merge_all`` in the master config works for me.

**Comment by terminalmage** [comment]
@ccrivelli thanks! I took a look at the docs and found that the top file merging stuff is only there for the minion config file docs. So I opened https://github.com/saltstack/salt/pull/38904 to correct this.

**Comment by TCShain** [comment]
Hey all,

I'm a salt noobie, but figured I'd share my experience.
I have a top file with a few hundred minions, and a small typo in my yaml invalidated the top file, which caused every high state to get this error.

Throwing my top file into a yaml validator quickly identified the issue.
Hope this helps someone catch this silly problem.

**Comment by piersf** [comment]
@TCShain thanks for that! I hit the same. One missing ":" was causing the above error.

**Comment by Lucianovici** [comment]
I read this thread 3 times, trying to figure out what was wrong in my setup, using v3005.1. Of course it was something as stupid as **minion id underscores vs dash**. It was obvious that couldn't match.

It was the "B) couldn't match the minion to any set of states in any of the top files it found." from https://github.com/saltstack/salt/issues/38719#issuecomment-273640756

These were some of the commands helped me troubleshoot.

`salt '*' state.show_top saltenv=staging`
`salt '*' slsutil.renderer salt://top.sls saltenv=staging`

BTW I use `top_file_merging_strategy: same` on master config, since each of my branches contain a `top.sls` file and I want to keep them isolated.
