### ISSUE TITLE
file.copy with preserve: True does not preserve ownership

### ISSUE THREAD

**Issue by adammichalik** [saltstack/salt#40154]
### Description of Issue/Question
Running `file.copy` with `preserve: True` does not preserve ownership (resets to root/user under which salt is running). The access permissions are preserved, though.

### Setup
On master:

```
# cat /srv/salt/copy.sls
/file_target:
  file.copy:
    - source: /file_source
    - preserve: True
```

On minion:
```
# ls -l /file_source
-rwx-w--wt 1 mysql mysql 0 Mar 20 15:17 /file_source*
```

### Steps to Reproduce Issue
On master:
```
# salt 'minion' state.apply copy
```

On minion:
```
# ls -l /file_target
-rwx-w--wt 1 root root 0 Mar 20 15:34 /file_target*
```
### Versions Report
Minion:
```
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```
Master is running `2016.3.3 (Boron)`

**Comment by gtmanfred** [comment]
@terminalmage while you are busy in the file state, you might want to take a look at this.

I have verified this on 2016.11 as well.

Thanks,
Daniel

**Comment by narendraingale2** [comment]
This is already fixed by this PR.
https://github.com/saltstack/salt/pull/40030

**Comment by adammichalik** [comment]
I must have missed #39445 - closing this as a duplicate. Thanks for fixing it already!

**Comment by gtmanfred** [comment]
I have marked the fix to be backported to 2016.11 as well.

Thanks @narendraingale2

**Comment by sastorsl** [comment]
Still not working as expected, neither with preserve=True or False.
With makedirs=True I see that the created directories gets the correct owner, but not group, while the actual file still is owned by root.

**Comment by davidkarlsen** [comment]
@sastorsl Open a new issue for it with?

**Comment by sastorsl** [comment]
Working on some examples.
