### ISSUE TITLE
grain ip6_interfaces empty

### ISSUE THREAD

**Issue by mweinelt** [saltstack/salt#41370]
### Description of Issue/Question

Since the upgrade from `2016.11.4+ds-2` to `2016.11.5+ds-2` on Debian Jessie the `ip6_interfaces` grains has become non-existant.

`ip4_interfaces` and `ip_interfaces` are looking good.

### Steps to Reproduce Issue

```
# salt 'gw02.*' grains.get ip6_interfaces
gw02.darmstadt.freifunk.net:
```

### Versions Report

```
# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.8 
        machine: x86_64
        release: 4.9.0-0.bpo.2-amd64
         system: Linux
        version: debian 8.8 
```

**Comment by marnovdm** [comment]
Just ran into this as well, breaks some of our states. Did a diff between 2016.11.4 and 2016.11.5 and it seems ipv6: True is now required in the config for this grain to be available. We were running ipv6: False because when I set it to enabled, even though we have an IPv6 environment, I get the following errors:

2017-05-22 09:25:13,208 [salt.utils       ][ERROR   ][5887] DNS lookup or connection check of 'salt.ourdomain.tld' failed.
2017-05-22 09:25:13,209 [salt.minion      ][ERROR   ][5887] Master hostname: 'salt.ourdomain.tld' not found or not responsive. Retrying in 30 seconds
2017-05-22 09:25:43,254 [salt.utils       ][ERROR   ][5887] DNS lookup or connection check of 'salt.ourdomain.tld' failed.
2017-05-22 09:25:43,255 [salt.minion      ][ERROR   ][5887] Master hostname: 'salt.ourdomain.tld' not found or not responsive. Retrying in 30 seconds
2017-05-22 09:26:13,290 [salt.utils       ][ERROR   ][5887] DNS lookup or connection check of 'salt.ourdomain.tld' failed.
2017-05-22 09:26:13,291 [salt.minion      ][ERROR   ][5887] Master hostname: 'salt.ourdomain.tld' not found or not responsive. Retrying in 30 seconds

So it seems there is no way for me to enable the ip6_interfaces grain anymore :( The DNS record from the master only resolves on IPv4 so perhaps that has something to do with it. But it seems strange to me that you'd have to run the master over IPv6 in order to get internal IPv6 support.

**Comment by mweinelt** [comment]
I can confirm, that after enabling `ipv6` on the salt-minion it reports `ip6_interfaces` again.

**Comment by Ch3LL** [comment]
I believe this is resolved here: https://github.com/saltstack/salt/pull/41244

As you can see from the note in the [Release Notes](https://docs.saltstack.com/en/latest/topics/releases/2016.11.5.html#patched-packages) we patched our packages with this fix. Are you guys using the packages, pip install or git install?

**Comment by mweinelt** [comment]
@Ch3LL We're using the Debian package repository at `deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main`.

Thanks for the feedback.

**Comment by marnovdm** [comment]
I'm using the Debian packages as well from deb http://repo.saltstack.com/apt/debian/8/amd64/latest jessie main.

Also, the other issue I mentioned when enabling IPv6 happened when upgrading to 2016.11.4. It seems with these 2 issues combined I still can't get ip6_interfaces grain available. Any thoughts on the connection issues when enabling ipv6: True (or, even when 'ipv6' is not in config)? I read about some connection/DNS determination changes in the 2016.11.4 release and feel it's related to that, but haven't been able to fix it yet.

**Comment by gtmanfred** [comment]
I am able to replicate this issue.

@dmurphy18 can you verify that the patch made it onto debian 8, because i am seeing the unpatched code on jessie.

Thanks,
Daniel

**Comment by Ch3LL** [comment]
The packages have been re-patched. Can you guys test here?
