### ISSUE TITLE
Salt Installer needs to kill related python process before install

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#42862]
### Description of Issue/Question
Additional fixes for the NSIS installer to address situations where salt is run in a cmd window instead of as a service. If the user tries to update salt via `pkg.install salt-minion` the python processes are not killed and there are locked files. This keeps salt from updating needed files and leaves the installation in an unknown state.

This is what the installer needs to do:
- Check for running python processes (specifically `c:\salt\bin\python.exe`) and close those
- This check would need to account for salt being installed in alternate locations in the future, so maybe pull a registry entry to get the location of the salt python binary

This is a continuation of #40947

**Comment by markuskramerIgitt** [comment]
I would like to name the salt process "salt-minion.exe"

Advantages: 
 - the location of python.exe must not be checked against c:\salt\bin (or a future location)
 - the task manager informs about the minion (instead of python.exe).

I remember there is a module that can give python procesess names, but I cannot find it again.

Ther easiest option is to directly rename c:\salt\bin\python.exe :
https://stackoverflow.com/questions/38420116/make-python-process-name-more-explicit

What do you think?

**Comment by twangboy** [comment]
This one maybe: https://pypi.python.org/pypi/setproctitle
We might be able to do something with iexpress to actually convert the batch file's to exe's or something...
https://stackoverflow.com/a/26797258

**Comment by damon-atkins** [comment]
Now that the termination time is increase to 27 secs away from the initial Control-C. This should not be required. Or their is a bug in how Control-C is managed.

Where is the minion code which loops around waiting for the next request?

**Comment by damon-atkins** [comment]
`When nssm receives a stop command from the Windows service manager, or when it detects that the monitored application has exited, it tries to shut down the monitored application, and any subprocesses, gracefully. If the application's process tree does not exit promptly, nssm can forcibly terminate all processes and subprocesses belonging to the application.`

The above sounds good for the service.

For someone calling the installer with salt-call pkg.install/upgrade.   If their was a `salt-status task-wait <timeout>`, then the installer could wait until state had completed running before stopping the service.

For now I suggest adding sleep 5 seconds just before stopping the service (to match the 5 seconds in pkg.install recently added) See http://nsis.sourceforge.net/Reference/Sleep  5 Seconds

**Comment by damon-atkins** [comment]
Instead of `if pkg_name in ['salt-minion', 'salt-minion-py3']:`
Suggest line is change to an re.search('salt[\s-]*minion',pkg_name) is not None
This will allow people to create their own sls files for salt-minion upgrade
e.g.
my org salt minion:
installer: http://internal web site etc
And it will not name clash with the github sls version and still work

**Comment by dwoz** [comment]
I think at least part of this issue is caused by the fact the calling python process (salt) might have a handle on DLLs which are going to be replaced by a sub-process (pip). The pip process has a workaround to deal with handles which it owns, and it re-tries in case some other process is momentarily locking the file. [seen here](https://github.com/pypa/pip/blob/9.0.1/pip/utils/__init__.py#L106).

Under normal operation when calling pip from the command line, the permissions modifications and retry make things work okay on windows. When salt is calling pip from another python process the work around starts to beak down.

I'm not sure any of the solutions presented here will work since they have the potential of killing the salt process which is running the state. A couple of potential options are:

- call pip as a module inside the same process as salt (only on windows when modifying upgrading salt's internal python).
- patch pip's onerror handler to try a rename of the dll instead of just a permissions change.

**Comment by damon-atkins** [comment]
As far as I am aware this has been resolved. I am surprised its still open.

**Comment by dwoz** [comment]
I ran into this, but it was a slightly different use case. I was not upgrading the salt minion but trying to upgrade packages in salt's python environment on windows. Doing so in a state is un-reliable as the permissions thing crops up.

@twangboy can you speak to wether or not this is still an issue for the installer?

**Comment by twangboy** [comment]
@dwoz @damon-atkins The issue here is when you're running salt in a cmd prompt and you initiate and installation. The installer detects the service and removes it but does not detect that the python in `c:\salt\bin` is running salt in a cmd window. The install completes but leaves a corrupt salt installation.

**Comment by damon-atkins** [comment]
We change the minion install called by pkg.install to be in a schedule and not wait for the schedule to complete.  By the time the salt installer runs salt-call should have exited or by even by the time the service is stopped, salt-call should be existed...  The uninstall might not be able to remove c:\salt\bin if the user ran the command from here, but it should be able to remove and replace everything else
????????

**Comment by marbx** [comment]
For what it's worth, the msi installer kills all salt related python processes before upgrade or uninstall
https://github.com/saltstack/salt-windows-msi/blob/6e8c18028f20190c8493d44108420e54270934f6/CustomAction01/CustomAction01.cs#L242

**Comment by damon-atkins** [comment]
@marbx I hope you stop the windows service first, as the service can be configure to restart the services on failure.
