### ISSUE TITLE
salt crashes after upgrading to 2017.7.0

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#42937]
### Description of Issue/Question
```
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.highstate
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')
[DEBUG   ] LazyLoaded highstate.output
local:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3629, in call_highstate
    top = self.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3089, in get_top
    tops = self.get_tops()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2787, in get_tops
    saltenv
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 495, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1044, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
TypeError: 'bool' object is not iterable

root@vm01:~#
```
### Steps to Reproduce Issue
`salt-call state.highstate -l debug`

### Versions Report
```
root@vm01:~# salt-call --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.8.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-92-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by garethgreenaway** [comment]
@zerthimon Thanks for the report.  A couple questions.  What version were you upgrading from?  Are you able to restart Salt and have it function again?

**Comment by garethgreenaway** [comment]
@zerthimon To be clear is Salt crashing on startup or only following a highstate?

**Comment by zerthimon** [comment]
@garethgreenaway It happens when I run a highstate.

**Comment by garethgreenaway** [comment]
@zerthimon Thanks.  So a call to a state function in one of the states that is being called via the highstate is causing the crash.  Are you able to narrow that down or provide the state files that are being used during a highstate?

**Comment by zerthimon** [comment]
@garethgreenaway Something weird is going on when trying to run a single state:
```
root@vm01:~# salt-call state.sls backup

Passed invalid arguments: 'bool' object is not iterable.

Usage:

    Execute the states in one or more SLS files
...
...
```
And the highstate just fails with exception

**Comment by garethgreenaway** [comment]
@zerthimon Is it just that state that is causing the issue or any single state?

**Comment by zerthimon** [comment]
@garethgreenaway any single state. Same error even if I provide a name of a non-existent state.

**Comment by zerthimon** [comment]
```
root@vm01:~# salt-call state.sls backup -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: vm01.internal.domain
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Found 'auths' section
[DEBUG   ] Found entry (registry=u'registry.internal.domain', username=u'registry')
[DEBUG   ] "GET /v1.22/version HTTP/1.1" 200 225
[DEBUG   ] "GET /v1.22/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 HTTP/1.1" 200 None
[DEBUG   ] "GET /v1.22/images/json?only_ids=0&all=0 HTTP/1.1" 200 None
[DEBUG   ] "GET /v1.22/info HTTP/1.1" 200 1948
[DEBUG   ] "GET /v1.22/networks?filters=%7B%7D HTTP/1.1" 200 None
[DEBUG   ] "GET /v1.22/volumes HTTP/1.1" 200 768
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9580)
[DEBUG   ] Setting zmq_reconnect_ivl to '9580ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_80c092637c_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_80c092637c_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_80c092637c_pull.ipc
[DEBUG   ] Sending event: tag = salt/auth/creds; data = {'_stamp': '2017-08-17T15:57:27.055901', 'creds': {'publish_port': 4505, 'aes': 'WQS3X5yXn86OVgOEcYkEfirr3c34/3JNJtPVrfOm5/wnQepBFvDyfBcHcjqrnrblYULLQSr6MR0=', 'master_uri': 'tcp://10.255.121.5:4506'}, 'key': ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')}
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'vm01.internal.domain', 'tcp://10.255.121.5:4506')
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render

Passed invalid arguments: 'bool' object is not iterable.

Usage:

    Execute the states in one or more SLS files

    test
        Run states in test-only (dry-run) mode

    pillar
        Custom Pillar values, passed as a dictionary of key-value pairs

        .. code-block:: bash

            salt '*' state.apply test pillar='{"foo": "bar"}'

        .. note::
            Values passed this way will override Pillar values set via
            ``pillar_roots`` or an external Pillar source.

        .. versionchanged:: 2016.3.0
            GPG-encrypted CLI Pillar data is now supported via the GPG
            renderer. See :ref:`here <encrypted-cli-pillar-data>` for details.

    pillar_enc
        Specify which renderer to use to decrypt encrypted data located within
        the ``pillar`` value. Currently, only ``gpg`` is supported.

        .. versionadded:: 2016.3.0

    queue : False
        Instead of failing immediately when another state run is in progress,
        queue the new state run to begin running once the other has finished.

        This option starts a new thread for each queued state run, so use this
        option sparingly.

    concurrent : False
        Execute state runs concurrently instead of serially

        .. warning::

            This flag is potentially dangerous. It is designed for use when
            multiple state runs can safely be run at the same time. Do *not*
            use this flag for performance optimization.

    saltenv
        Specify a salt fileserver environment to be used when applying states

        .. versionchanged:: 0.17.0
            Argument name changed from ``env`` to ``saltenv``.

        .. versionchanged:: 2014.7.0
            If no saltenv is specified, the minion config will be checked for an
            ``environment`` parameter and if found, it will be used. If none is
            found, ``base`` will be used. In prior releases, the minion config
            was not checked and ``base`` would always be assumed when the
            saltenv was not explicitly set.

    pillarenv
        Specify a Pillar environment to be used when applying states. This
        can also be set in the minion config file using the
        :conf_minion:`pillarenv` option. When neither the
        :conf_minion:`pillarenv` minion config option nor this CLI argument is
        used, all Pillar environments will be merged together.

    localconfig

        Optionally, instead of using the minion config, load minion opts from
        the file specified by this argument, and then merge them with the
        options from the minion config. This functionality allows for specific
        states to be run with their own custom minion configuration, including
        different pillars, file_roots, etc.

    mock:
        The mock option allows for the state run to execute without actually
        calling any states. This then returns a mocked return which will show
        the requisite ordering as well as fully validate the state run.

        .. versionadded:: 2015.8.4

    CLI Example:

    .. code-block:: bash

        salt '*' state.sls core,edit.vim dev
        salt '*' state.sls core exclude="[{'id': 'id_to_exclude'}, {'sls': 'sls_to_exclude'}]"

        salt '*' state.sls myslsfile pillar="{foo: 'Foo!', bar: 'Bar!'}"
    
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1095, in sls
    high_, errors = st_.render_highstate({opts['environment']: mods})
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3519, in render_highstate
    sls, saltenv, mods, matches)
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3173, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 404, in get_state
    dest = self.cache_file(path, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 495, in get_url
    result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1044, in get_file
    hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
TypeError: 'bool' object is not iterable
root@vm01:~#
```

**Comment by garethgreenaway** [comment]
@zerthimon Seems like the bug you found is related to another reported issue which was fixed by PR #42860 which will go into 2017.7.2.

**Comment by garethgreenaway** [comment]
Looking closer might be related but probably not the cause.  Digging deeper.

**Comment by grobinson-blockchain** [comment]
We're experiencing the same issue with 2017.7.1. The issue also occurs on instances that have not had previous versions installed either.

    local:
        Data failed to compile:
    ----------
        Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3629, in call_highstate
        top = self.get_top()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3089, in get_top
        tops = self.get_tops()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2787, in get_tops
        saltenv
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
        return self.get_url(path, '', True, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 495, in get_url
        result = self.get_file(url, dest, makedirs, saltenv, cachedir=cachedir)
      File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 1044, in get_file
        hash_server, stat_server = self.hash_and_stat_file(path, saltenv)
    TypeError: 'bool' object is not iterable

version report:

    Salt Version:
               Salt: 2017.7.1

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1

    System Versions:
               dist: debian 9.0
             locale: UTF-8
            machine: x86_64
            release: 4.9.0-3-amd64
             system: Linux
            version: debian 9.0

**Comment by grobinson-blockchain** [comment]
@garethgreenaway I tried the patch in https://github.com/saltstack/salt/pull/42860 but I'm afraid I still get the same error.  I'll report back with more information when I've found the root cause.

**Comment by grobinson-blockchain** [comment]
The issue appears to be that `self.channel.send(load)` in `__hash_and_stat_file` can return False (see https://github.com/saltstack/salt/blob/2017.7.1/salt/fileclient.py#L1270) where the [caller](https://github.com/saltstack/salt/blob/2017.7.1/salt/fileclient.py#L1044) expects two return values.

The exception occurs because of the following:

    >>> a, b = False
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'bool' object is not iterable

**Comment by grobinson-blockchain** [comment]
This errors appears to happen because the salt master is on an older version than the minion:

    2017-08-18 14:00:39,048 [salt.master      ][ERROR   ][18046] Received function _file_hash_and_stat which is unavailable on the master, returning False

the fix is to update the salt master to 2017.7.1

**Comment by garethgreenaway** [comment]
@grobinson-blockchain Thanks.
@zerthimon Can you confirm that you're salt master & salt minions are all either 2017.7.0 or 2017.7.1?

**Comment by zerthimon** [comment]
@garethgreenaway My salt-master is 2016.11.6...

**Comment by grobinson-blockchain** [comment]
You need to update the master to the latest version. The minion is attempting to call methods on the master that don't exist in the older version.

**Comment by zerthimon** [comment]
@grobinson-blockchain Thanks a lot for the investigation.
I'll be upgrading the master a bit later. For now I've reverted the minion back to 2016.11.6 so It can work.

This issue can be closed.

**Comment by garethgreenaway** [comment]
@grobinson-blockchain Thanks for the info. on this one.  

@zerthimon If the issue persists please feel free to re-open this issue.
