### ISSUE TITLE
ldap.managed broken with 2018.3.0

### ISSUE THREAD

**Issue by julientravelaer** [saltstack/salt#46887]
### Description of Issue/Question
We are unable to add/modify entries in LDAP using state.ldap since upgrade to 2018.3.0
Everything is working fine when we rollback to salt 2017.7.5+ds-1

### Setup
Content of the state file:
```
ldap_roles_groups:
  ldap.managed:
    - connect_spec:
       url: {{ ldap_url }}
       bind:
         method: simple
         dn: {{ ldap_dn }}
         password: {{ ldap_password }}
    - entries:
      {% for group in ldap['groups'] %}
      - '{{ group.fqdn }}':
        - default:
            objectClass:
              - group
              - top
            cn:
              - {{ group.name }}
            name:
              - {{ group.name }}
            sAMAccountName:
              - {{ group.name }}
      {% endfor %}
```

Returned error:
```          ID: ldap_roles_groups
    Function: ldap.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1878, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/ldap.py", line 334, in managed
                  __salt__['ldap3.add'](l, dn, n)
                File "/usr/lib/python2.7/dist-packages/salt/modules/ldap3.py", line 412, in add
                  l.c.add_s(dn, modlist)
                File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 209, in add_s
                  msgid = self.add(dn,modlist)
                File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 206, in add
                  return self.add_ext(dn,modlist,None,None)
                File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 191, in add_ext
                  return self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
                File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 106, in _ldap_call
                  result = func(*args,**kwargs)
              TypeError: ('expected a string in the list', u'group')
     Started: 09:02:00.034829
    Duration: 51.893 ms
     Changes:
```

### Versions Report
```Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.9.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1054-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by rallytime** [comment]
This looks related to #46859

@terminalmage FYI

**Comment by terminalmage** [comment]
Should be fixed by https://github.com/saltstack/salt/pull/47029

**Comment by terminalmage** [comment]
I don't have an LDAP setup available for testing, however.

**Comment by rallytime** [comment]
@julientravelaer Are you in a position to test the fix above?

**Comment by nullify005** [comment]
@julientravelaer have a look at the linked PR, I believe this solves the issue with ldap modify operations (I was getting the same issue too)

**Comment by julientravelaer** [comment]
@nullify005 Your PR fixes this problem thx a lot !

But an other remain, I have some a state which add member to ldap group, and it still fails:

```
ldap_user_group_{{ username }}:
  ldap.managed:
    - connect_spec:
       url: {{ ldap_url }}
       bind:
         method: simple
         dn: {{ ldap_dn }}
         password: {{ ldap_password }}
    - entries:
      - '{{fqdn}}':
        - add:
            member: 'CN={{ username }},{{ ldap_basedn }}'
```
This state fails with :
```
          ID: ldap_user_group_testAccount
    Function: ldap.managed
      Result: False
     Comment: failed to modify entry CN=xxxxx,CN=xxxx,DC=xxxx,DC=xxxx(exception in ldap backend: UNWILLING_TO_PERFORM({'info': '00002035: objectclass: modify message must have elements/attributes!', 'desc': 'Server is unwilling to perform'},))
     Started: 07:24:39.190373
    Duration: 13.285 ms
     Changes:
```

As the previous problem, everything is ok when I rollback to 2017.7.6

**Comment by angeloudy** [comment]
I am getting a different error `TypeError: ('expected a byte string in the list',`. I am running python3.6.
I think a check of `if PY2` is needed before `to_str = True`

```
                File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/states/ldap.py", line 327, in managed
                  __salt__['ldap3.change'](l, dn, o, n)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/ldap3.py", line 592, in change
                  l.c.modify_s(dn, modlist)
                File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 600, in modify_s
                  return self.modify_ext_s(dn,modlist,None,None)
                File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 572, in modify_ext_s
                  msgid = self.modify_ext(dn,modlist,serverctrls,clientctrls)
                File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 569, in modify_ext
                  return self._ldap_call(self._l.modify_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
                File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 294, in _ldap_call
                  result = func(*args,**kwargs)
              TypeError: ('expected a byte string in the list', 'tao')
```

**Comment by terminalmage** [comment]
Can you please open a new issue, then?
