### ISSUE TITLE
Salt-Cloud fails to create VMware Snapshot from orchestrator on second run. 

### ISSUE THREAD

**Issue by rbthomp** [saltstack/salt#50323]
### Description of Issue/Question
I have an orchestration job that creates a VMware snapshot when called by a reactor. In many instances multiple events come in firing off multiple orchestration jobs to create VMware snapshots. The first time a flood of events come in the VMware snapshots are created without issues, but anytime a flood of events comes in after that snapshots fail to be created. The strange thing is if I call `salt-cloud` directly I can create the snapshots without issues, even when the orchestration job fails to create them. I can correct this by restarting the `salt-master`, after which I can create snapshots for the first flood of events, but sub-sequential  events fail. 

IT looks like salt-cloud fails authentication after the first sent of received events. This is not a VMware permissions issue as the first orchestration jobs that run succeed, and if I restart `salt-master` it works for the first set of events.

### Setup
- Setup a salt-cloud environment with a VMware provider. 

_reactor/test.sls
```
run_test_orch:
  runner.state.orchestrate:
    - args:
      - mods: orch.test
      - pillar:
          server: {{ data['id'] }}
```
orch/test.sls
```
{% set server = salt['pillar.get']('server') %}

create_snapshot:
  salt.runner:
    - name: cloud.action
    - func: create_snapshot
    - instance: {{ server.split('.')[0] }}
    - snapshot_name: test snapshot
    - description: test snapshot
    - memdump: False
```

- Create events on the event bus that fire of the orchestration job. 
- You can do this by creating a test event state.

test/test.sls
```
test_orch:
  event.send:
    - data:
      status: 'test'
```

### Logs
```
EBUG   ] Rendered data from file: /var/cache/salt/master/files/base/orch/test.sls:


create_snapshot:
  salt.runner:
    - name: cloud.action
    - func: create_snapshot
    - instance: Hostname
    - snapshot_name: test snapshot
    - description: test snapshot
    - memdump: False

[DEBUG   ] Results of YAML rendering:
OrderedDict([(u'create_snapshot', OrderedDict([(u'salt.runner', [OrderedDict([(u'name', u'cloud.action')]), OrderedDict([(u'func', u'create_snapshot')]), OrderedDict([(u'instance', u'Hostname')]), OrderedDict([(u'snapshot_name', u'test snapshot')]), OrderedDict([(u'description', u'test snapshot')]), OrderedDict([(u'memdump', False)])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/master/files/base/orch/test.sls' using 'yaml' renderer: 0.00243091583252
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded salt.runner
[INFO    ] Running state [cloud.action] at time 17:11:11.695028
[INFO    ] Executing state salt.runner for [cloud.action]
[DEBUG   ] Unable to fire args event due to missing __orchestration_jid__
[DEBUG   ] LazyLoaded saltutil.runner
[DEBUG   ] LazyLoaded cloud.action
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/afcu.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/afcu.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/beacons.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/beacons.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/salt_events.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/salt_events.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/susemanager-mine.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/susemanager-mine.conf
[DEBUG   ] Changed git to gitfs in minion opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master.somedomain.local
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20181030171112123958/new; data = {u'fun': u'runner.cloud.action', u'fun_args': [{u'instance': u'Hostname', u'memdump': False, u'snapshot_name': u'test snapshot', u'description': u'test snapshot', u'func': u'create_snapshot'}], u'jid': u'20181030171112123958', u'user': u'UNKNOWN', u'_stamp': '2018-10-30T23:11:12.198675'}
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Gathering reactors for tag salt/run/20181030171112123958/new
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master.somedomain.local
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/vmware.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/vmware.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad vmware.optimize_providers: 'vmware.optimize_providers' is not available.
[DEBUG   ] The 'vmware' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[ERROR   ] (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The session is not authenticated.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 803, in get_content
    container_ref, [obj_type], True)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1370, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The session is not authenticated.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}
[DEBUG   ] Failed to execute 'vmware.list_nodes_min()' while querying for running nodes: Not enough permissions. Required privilege: System.View
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2393, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 1617, in list_nodes_min
    vm_list = salt.utils.vmware.get_mors_with_properties(_get_si(), vim.VirtualMachine, vm_properties)
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 947, in get_mors_with_properties
    content = get_content(*content_args, **content_kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/vmware.py", line 808, in get_content
    '{}'.format(exc.privilegeId))
VMwareApiError: Not enough permissions. Required privilege: System.View
. Removed list of systems provied from vsphere.
.
.
..
.
.
..
.

[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20181030171112123958: []
[DEBUG   ] Sending event: tag = salt/run/20181030171112123958/ret; data = {u'fun_args': [{u'instance': u'Hostname', u'memdump': False, u'snapshot_name': u'test snapshot', u'description': u'test snapshot', u'func': u'create_snapshot'}], u'jid': u'20181030171112123958', u'return': {u'Not Found': [u'Hostname'], u'Not Actioned/Not Running': [u'Hostname']}, u'success': True, u'_stamp': '2018-10-30T23:11:14.064183', u'user': u'UNKNOWN', u'fun': u'runner.cloud.action'}
[INFO    ] Runner completed: 20181030171112123958
[INFO    ] {u'return': {u'Not Found': [u'Hostname'], u'Not Actioned/Not Running': [u'Hostname']}}
[INFO    ] Completed state [cloud.action] at time 17:11:14.065592 (duration_in_ms=2370.565)
[DEBUG   ] File /var/cache/salt/master/accumulator/140632157446800 does not exist, no need to cleanup
[DEBUG   ] Gathering reactors for tag salt/run/20181030171112123958/ret
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20181030171111082818: []
[DEBUG   ] Sending event: tag = salt/run/20181030171111082818/ret; data = {u'fun_args': [{u'pillar': OrderedDict([(u'server', u'Hostname.afcucorp.test')]), u'mods': u'orch.test'}], u'jid': u'20181030171111082818', u'return': {u'outputter': u'highstate', u'data': {u'salt-master.somedomain.local': {u'salt_|-create_snapshot_|-cloud.action_|-runner': {u'comment': u"Runner function 'cloud.action' executed.", u'name': u'cloud.action', u'__orchestration__': True, u'start_time': '17:11:11.695027', u'result': True, u'duration': 2370.565, u'__run_num__': 0, u'__jid__': u'20181030171112123958', u'__sls__': u'orch.test', u'changes': {u'return': {u'Not Found': [u'Hostname'], u'Not Actioned/Not Running': [u'Hostname']}}, u'__id__': u'create_snapshot'}}}, u'retcode': 0}, u'success': True, u'_stamp': '2018-10-30T23:11:14.108159', u'user': u'Reactor', u'fun': u'runner.state.orchestrate'}
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
salt-master.somedomain.local:
----------
          ID: create_snapshot
    Function: salt.runner
        Name: cloud.action
      Result: True
     Comment: Runner function 'cloud.action' executed.
     Started: 17:11:11.695027
    Duration: 2370.565 ms
     Changes:
              ----------
              return:
                  ----------
                  Not Actioned/Not Running:
                      - Hostname
                  Not Found:
                      - Hostname

Summary for salt-master.somedomain.local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.371 s
[INFO    ] Runner completed: 20181030171111082818
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
was this previously working on an older version?

also ping @saltstack/team-cloud any ideas here?

**Comment by rbthomp** [comment]
@Ch3LL I'm not sure I just implemented this on 2018.3.3.

**Comment by sagetherage** [comment]
not stale

**Comment by Ch3LL** [comment]
as you point out with this error: `msg = "The object 'vim.view.ContainerView:session[52cc35f2-f7df-209b-fd4f-1574410b47ec]52ac5f07-30d7-6d44-ad51-95f635eb8686' has already been deleted or has not been completely created",` ooks like for some reason we aren't keeping the same authenticated session, will need to get this fixed.

**Comment by Dejv56** [comment]
I am still experiencing the same "The session is not authenticated" error when using salt.utils.vmware.get_service_instance to create instance object in custom proxy module. I am running v3002.2, but i tried to upgrade utils module to master branch, but problem is persistent.

Proxy minion is returning data for several minutes/hours without a hitch and suddenly i get error and only way to fix it is restarting proxy minion. Then it works again, for some time.

It's weird that software acquired by VMware doesn't provide tools to manage Vsphere/ESX properly. Salt Extension module for SaltStack is nice but its still in developement. Even when finished, the rest api is very limited in comparison to soap api, for example managing snapshots is not existent.

**Comment by dwoz** [comment]
Closing — the underlying `salt.utils.vmware.get_service_instance` cached-session reconnect path was fixed in #69233 (merged 2026-06-06, present on 3006.x / 3007.x / 3008.x / master). It now reconnects on `vim.fault.NotAuthenticated` (the exact error in this report) as well as the socket-level errors (`ssl.SSLError` / `BrokenPipeError` / `ConnectionResetError`) that arise when salt-cloud's `map_providers_parallel` fork inherits the cached pyVmomi service instance — the scenario described here (reactor → orchestration → `runner.cloud.action` on repeat). Please reopen if you can still reproduce on a current release.
