### ISSUE TITLE
Release a debian 10 buster repository 

### ISSUE THREAD

**Issue by rgarrigue** [saltstack/salt#52371]
Hi

Debian 10 "Buster" should be out soon, it's in hard freeze state atm. When will you release a matching repository ? At least shipping the agents if not the server.

Best regards,

**Comment by frogunder** [comment]
@dmurphy18 Do you have any info/input on this? Thanks.

**Comment by dmurphy18** [comment]
@rgarrigue Waiting on fix salt handling python-tornado > v5.  Once that is available, then will be able to update support for Buster. A fix is currently under test.

Currently there is the Debian Salt support for Salt 2018.3.4 that comes with Buster.

As soon as the issues with v5.x of python-tornado and Salt are resolved, then packages will be made available, given build times / schedule.  Noting that currently Buster has python3-tornado v5.1.1.
Fedora is waiting for this fix too.

This can be tracked in the GitHub repository for salt packaging on Python3, https://github.com/saltstack/salt-pack-py3/issues/116, the correct place for packaging issues with Python 3.

Hence closing this here.

**Comment by disaster123** [comment]
I still can't find any buster repo here? http://repo.saltstack.com/apt/debian/

**Comment by pubyun** [comment]
need package for Debian 10 (Buster)

**Comment by konstanting-kaymera** [comment]
@dmurphy18 can you reopen the issue, please.
Thank you

**Comment by disaster123** [comment]
Does this mean the Debian 10 buster release only support py3? Py3 is currently far slower than py2 with salt - i'm currently running the py2 packets of Stretch on Buster which works fine.

**Comment by xsherlockpl** [comment]
hi, any update on that, I have done all my RPI sensors to buster and, hit that wall.

**Comment by disaster123** [comment]
@xsherlockpl As far as i know the buster repo should come with 2019.2.1 - but no idea when this will happen.

You can just add the debian 9 py2 repo - this works fine for me under buster except for some bugs 2019.2 has.

**Comment by SynPrime** [comment]
Out now for Debian 10: https://repo.saltstack.com/#debian

**Comment by mainjoehere** [comment]
The debian 10 packages are not available on http://repo.saltstack.com. The directories are empty - only an archive dir exists. Can someone make them available, please?

**Comment by dmurphy18** [comment]
@mainjoehere Please read the Warning message, about OS support introduced in 2019.2.1.
The archive path http://repo.saltstack.com/py3/debian/10/amd64/archive/2019.2.1 exists to allow access. It is hoped that finally Salt 2019.2.2 will be released next week unless QA find something major broken.
