### ISSUE TITLE
GitPython

### ISSUE THREAD

**Issue by malekerramli** [saltstack/salt#52510]
### Description of Issue/Question
GitPython return 'True', but the GitHub repo is not fetched

### Setup
master_sign_pubkey: True
autosign_file: /etc/salt/autosign.conf
fileserver_backend:
  - git
  - roots
gitfs_provider: gitpython
gitfs_base: salt-poc (branch name)
gitfs_remotes:
  - ssh://git@github.com:********/**********.git

### Ssh folder 

drwx------. 2 root root  107 Apr 11 18:24 .
dr-xr-x---. 4 root root  182 Apr 11 16:45 ..
-rw-------. 1 root root  553 Apr 11 15:49 authorized_keys
-rw-r--r--. 1 root root  152 Apr 11 18:24 config
-rw-r--r--. 1 root root  803 Apr 11 16:59 known_hosts
-rw-------. 1 root root 3243 Apr 11 17:13 ssh-git-ro.priv
-rw-r--r--. 1 root root  739 Apr 11 17:13 ssh-git-ro.pub

### SSH config
Host github.com
    Hostname github.com
    PreferredAuthentications publickey
    StrictHostKeyChecking no
    IdentityFile /root/.ssh/ssh-git-ro.priv

### Steps to Reproduce Issue
GitCommandError: 'Error when fetching: fatal: Could not read from remote repository.' returned with exit code 2
2019-04-11 19:45:07,224 [salt.utils.gitfs :2345][ERROR   ][21558] Exception caught while fetching gitfs remote 'ssh://git@github.com:*****/********': 'Error when fetching: fatal: Could not read from remote repository.' returned with exit code 2
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 2333, in fetch_remotes
    if repo.fetch():
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 767, in fetch
    return self._fetch()
  File "/usr/lib/python2.7/site-packages/salt/utils/gitfs.py", line 1253, in _fetch
    fetch_results = origin.fetch()
  File "/usr/lib/python2.7/site-packages/git/remote.py", line 651, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/lib/python2.7/site-packages/git/remote.py", line 559, in _get_fetch_info_from_stderr
    raise GitCommandError(("Error when fetching: %s" % line,), 2)

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

i tried everything under the sun ...

**Comment by mattp-** [comment]
try pygit2 instead?

**Comment by malekerramli** [comment]
> try pygit2 instead?

i tried to...

**Comment by mattp-** [comment]
Malek, did you encounter separate problems with it? I just know pygit2 is the most commonly used interface, and least likely to encounter issues

**Comment by malekerramli** [comment]
i figured out the issue with GitPython... works just fine

**Comment by xenadmin** [comment]
@malekerramli How did you get it to work? I'm currently getting nuts trying to get gitfs working on Debian 9 with salt 2018.3.4 with either gitpython or pygit2 and both fail me.

**Comment by jryden** [comment]
This may be a separate issue report... On Amazon Linux 2 all versions of GitPython above 0.3.7 cause git processes to hang around and pile up - sample ps output:

`7439 ?        S      0:00 git cat-file --batch
 7440 ?        S      0:00 git cat-file --batch
 7441 ?        S      0:00 git cat-file --batch-check
 7442 ?        S      0:00 git cat-file --batch-check`

Since 0.3.7 is getting a little long in the tooth, to say the least, this should probably be fixed at some point...

**Comment by matthewsht** [comment]
jryden's report on Sep 10, 2019 is still happening in Saltstack v3005

**Comment by maltris** [comment]
3,5 years in: Just encountered an issue with the same symptoms on 3006.10 with gitpython 3.1.37. In an infrastructure of about 400 hosts it generates 15 such processes per minute. pygit2 in that constellation is not possible because of other constraints. Does anyone have an idea?
