### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#55310]
### Description of Issue
Support Python 3.8

Arch Linux updated to python 3.8 and one of the tests upgrades the system, which means, while the test suite runs, we upgrade from 3.7 to 3.8, thus failing at the very end.

https://jenkinsci.saltstack.com/job/pr-kitchen-archlts-py3/job/PR-55276/4/

Current stopgap: https://github.com/saltstack/salt/pull/55309

**Comment by s0undt3ch** [comment]
Problematic code:
- [ ] [`from platform import _supported_dists`](https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L40)

**Comment by Ch3LL** [comment]
- [ ] Need to have a running list of deprecation's which will affect Salt, for example: abc from collections in Py 3.8.  Plan to have public list in GitHub ? where contributors / Salt can add to the list and generate Issues such that Salt can be updated.

**Comment by Ikke** [comment]
For Alpine, the lack of python3.8 support prevents salt-minion from running, so this is not just a test failure, but actual run-time errors:

```
$ salt-minion
Traceback (most recent call last):
[..]
  File "/usr/lib/python3.8/site-packages/salt/grains/core.py", line 40, in <module>
    from platform import _supported_dists
ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)

**Comment by itamarjp** [comment]
Python 3.8 will land fedora soon. (already there for Fedora 32)
https://koji.fedoraproject.org/koji/packageinfo?packageID=9781

**Comment by Vaelatern** [comment]
This crops up after working around problems in issue  #56551

**Comment by chalbersma** [comment]
I think this will block support for Ubuntu 20.04 as it uses python3.8 by default.

**Comment by Ch3LL** [comment]
can you try this PR https://github.com/saltstack/salt/pull/56031?

**Comment by brianthelion** [comment]
@Ch3LL The `platform._supported_dists` issue had not be fixed as of yesterday. See #56752

**Comment by terminalmage** [comment]
It's not just `platform._supported_dists` that is gone in Python 3.8, it is also `platform.linux_distribution()`. This code was not being maintained and now no longer exists.

The core grains already support using [`distro`](https://pypi.org/project/distro/), which is the recommended replacement for `platform.linux_distribution()`.

We may want to consider adding `distro` as a new hard dependency and remove from the code any usage of `platform.linux_distribution()`. The only problem I can see with this approach is that we may lose some fidelity when it comes to the `osrelease` grain, due to the differences between the two modules:

```python
>>> import distro
>>> import platform
>>> distro.linux_distribution()
('CentOS Linux', '8', 'Core')
>>> platform.linux_distribution()
('CentOS Linux', '8.1.1911', 'Core')
```

**Comment by richardnpaul** [comment]
> It's not just `platform._supported_dists` that is gone in Python 3.8, it is also `platform.linux_distribution()`. This code was not being maintained and now no longer exists.
> 
> The core grains already support using [`distro`](https://pypi.org/project/distro/), which is the recommended replacement for `platform.linux_distribution()`.
> 
> We may want to consider adding `distro` as a new hard dependency and remove from the code any usage of `platform.linux_distribution()`. The only problem I can see with this approach is that we may lose some fidelity when it comes to the `osrelease` grain, due to the differences between the two modules:
> 
> ```python
> >>> import distro
> >>> import platform
> >>> distro.linux_distribution()
> ('CentOS Linux', '8', 'Core')
> >>> platform.linux_distribution()
> ('CentOS Linux', '8.1.1911', 'Core')
> ```

You should be able to dig out the full version number.  In the docs the example given is: 
```
$ python
>>> import distro
>>> distro.linux_distribution(full_distribution_name=False)
('centos', '7.1.1503', 'Core')
```

The full version number seems to be available from `distro.version(best=True)`, the default for this is unfortunately `False`.

**Comment by terminalmage** [comment]
Good catch. I'm going to add some logic to the core grains to get the "best" version.

**Comment by terminalmage** [comment]
Well, first I'm going to open an upstream bug report.

**Comment by richardnpaul** [comment]
What is a pain is that changing this leads to the Distribution Name not being returned fully.  I can't check, because I'm on Ubuntu, but maybe changing the version default to `best=True` in distro, or https://github.com/nir0s/distro/blob/d93643a066f72b1fea3864d30a407c2ee7ec7b44/distro.py#L681 adding best=True here so that `linux_distribution` returns the full version number by default (maybe and parameter could be added to turn this off again, like the `full_distrribution_name` one does.

**Comment by terminalmage** [comment]
I've opened an issue upstream and we'll see what comes of it.

> What is a pain is that changing this leads to the Distribution Name not being returned fully.

How so? It looks fine to me:

```python
>>> import platform
>>> import distro
>>> platform.linux_distribution()
('Ubuntu', '20.04', 'focal')
>>> distro.linux_distribution()
('Ubuntu', '20.04', 'focal')
```

**Comment by richardnpaul** [comment]
> I've opened an issue upstream and we'll see what comes of it.
> 
> > What is a pain is that changing this leads to the Distribution Name not being returned fully.
> 
> How so? It looks fine to me:
> 
> ```python
> >>> import platform
> >>> import distro
> >>> platform.linux_distribution()
> ('Ubuntu', '20.04', 'focal')
> >>> distro.linux_distribution()
> ('Ubuntu', '20.04', 'focal')
> ```
Sorry, I meant if you do this:
`distro.linux_distribution(full_distribution_name=False)`

**Comment by terminalmage** [comment]
OK, Salt doesn't do this though. It uses the full name.

**Comment by nergdron** [comment]
just ran into this problem, after upgrading some servers to the latest Ubuntu LTS (20.04). it's really surprising to me that this ticket's been open since last November and there still isn't Python 3.8 support, given that's what every major distro is moving to even in their LTS branches. is there a timeline for getting this fixed, now that it's likely to break a lot of production systems as folks upgrade?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ran into this as well.. Would be great to have this fixed soon.

**Comment by asvany** [comment]
this bug still alive on mandjaro linux.
"ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
"

**Comment by terminalmage** [comment]
@asvany `_supported_dists` is no longer referenced in Salt code as of the upcoming 3001 (Sodium) release, aside from in a comment.

```
% git show v3000:salt/grains/core.py | fgrep _supported_dists
from platform import _supported_dists
_supported_dists += ('arch', 'mageia', 'meego', 'vmware', 'bluewhite64',
# Please see os_data() and _supported_dists.
             linux_distribution(supported_dists=_supported_dists)]


% git show v3001rc1:salt/grains/core.py | fgrep _supported_dists
# Please see os_data() and _supported_dists.
```

**Comment by s0undt3ch** [comment]
@asvany As @terminalmage mentioned, this issue should be fixed.
What version of salt are you running?
Please try v3001rc1.

**Comment by asvany** [comment]
┌──[as@as17]─[/tmp]─[○]                                     [p jún 12 - 12:23]
└──● virtualenv py_env_salt
created virtual environment CPython3.8.3.final.0-64 in 391ms
  creator CPython3Posix(dest=/tmp/py_env_salt, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/as/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
┌──[as@as17]─[/tmp]─[○]                                     [p jún 12 - 12:23]
└──● . ./py_env_salt/bin/activate
(py_env_salt) ┌──[as@as17]─[/tmp]─[○]                       [p jún 12 - 12:24]
└──● pip install salt-ssh
Collecting salt-ssh
  Downloading salt-ssh-3000.3.tar.gz (15.2 MB)
     |████████████████████████████████| 15.2 MB 5.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /tmp/py_env_salt/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6vboudje/salt-ssh/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6vboudje/salt-ssh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yublgzzw
         cwd: /tmp/pip-install-6vboudje/salt-ssh/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-6vboudje/salt-ssh/salt/version.py", line 15, in <module>
        from platform import linux_distribution as _deprecated_linux_distribution
    ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6vboudje/salt-ssh/setup.py", line 126, in <module>
        exec(compile(open(SALT_VERSION).read(), SALT_VERSION, 'exec'))
      File "/tmp/pip-install-6vboudje/salt-ssh/salt/version.py", line 22, in <module>
        from distro import linux_distribution
    ModuleNotFoundError: No module named 'distro'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
(py_env_salt) ┌─[✗]──[as@as17]─[/tmp]─[○]                   [p jún 12 - 12:24]
└──●

**Comment by louwers** [comment]
Running `salt-ssh` with a target that has Python 3.8 installed still seems problematic.

```
$ sudo -E salt-ssh tgt test.ping
tgt:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        Install Python 2.6 / Python 3 Salt dependencies on the Salt SSH master 
        to interact with Python 2.6 / Python 3 targets
$ sudo -E salt-ssh -r tgt "python --version"
tgt:
    ----------
    retcode:
        0
    stderr:
    stdout:
        Python 3.8.3
```

**Comment by louwers** [comment]
`salt-ssh` doesn't seem to be working when only Python 3.8 is installed on the host.

```
$ sudo -E salt-ssh tgt test.ping
tgt:
    ----------
    retcode:
        10
    stderr:
    stdout:
        ERROR: Python version error. Recommendation(s) follow:
        Install Python 2.6 / Python 3 Salt dependencies on the Salt SSH master 
        to interact with Python 2.6 / Python 3 targets
$ sudo -E salt-ssh -r tgt "python --version"
tgt:
    ----------
    retcode:
        0
    stderr:
    stdout:
        Python 3.8.3
```

**Comment by Ch3LL** [comment]
@louwers i'm not seeing `from platform import _supported_dists` anywhere in the code for 3001.1. i'm guessing that is still the 2019.2.4 code on the target host. It should have updated it to 3001.1 but can you wipe that out `-w` and make sure you are still not seeing the issue?

**Comment by cobordism** [comment]
For the record, I am seeing the same error in qubesOS using a debian-11 template:

```
Error on updating debian-testing: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=debian-testing', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20
debian-testing:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_62a99a_salt/salt-call", line 27, in <module>
              salt_call()
            File "/var/tmp/.root_62a99a_salt/pyall/salt/scripts.py", line 440, in salt_call
              import salt.cli.call
            File "/var/tmp/.root_62a99a_salt/pyall/salt/cli/call.py", line 5, in <module>
              import salt.utils.parsers
            File "/var/tmp/.root_62a99a_salt/pyall/salt/utils/parsers.py", line 28, in <module>
              import salt.config as config
            File "/var/tmp/.root_62a99a_salt/pyall/salt/config/__init__.py", line 100, in <module>
              _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
            File "/var/tmp/.root_62a99a_salt/pyall/salt/config/__init__.py", line 89, in _gather_buffer_space
              import salt.grains.core
            File "/var/tmp/.root_62a99a_salt/pyall/salt/grains/core.py", line 40, in <module>
              from platform import _supported_dists
          ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib/python3.8/platform.py)
```

**Comment by s0undt3ch** [comment]
@cobordism which version of salt is that?

**Comment by s0undt3ch** [comment]
see @Ch3LL's comment above

**Comment by cobordism** [comment]
> @cobordism which version of salt is that?

I'm afraid I'm not sure. It's whatever is in Qubes 4.0.3.

dom0:
`salt-minion --version` gives me 2017.7.1 (Nitrogen), as does `salt-call --version` and `salt-proxy --version`
Those are all the salt-* commands I can see in the dom0 system.

AppVM:
However in the fedora appvm I can see `salt-ssh --version` as 3000.2.

Perhaps this is an issue I have to raise with Qubes? 
https://github.com/QubesOS?q=salt

**Comment by s0undt3ch** [comment]
Indeed, 2017.x is no longer supported.
