### ISSUE TITLE
Some Group Policies get reset upon a second run of lgpo.set

### ISSUE THREAD

**Issue by onnodb** [saltstack/salt#55579]
### Description of Issue

The `lgpo.set` state in `salt.states.win_lgpo` does not seem to preserve all previously set Local Group Policies when run twice (with different sets of policies).

### Setup

A sample `top.sls`:
```yaml
base:
  '*':
    - lgpo1
    - lgpo2
```

`lgpo1/init.sls`:
```yaml
LGPO 1:
  lgpo.set:
    - computer_policy:
        "Force a specific default lock screen and logon image":
          LockScreenImage: 'C:\Users\Public\Pictures\login_background.jpg'
          LockScreenOverlaysDisabled: True
```

`lgpo2/init.sls`:
```yaml
LGPO 2:
  lgpo.set:
    - computer_policy:
        "Turn off Autoplay":
            "Turn off Autoplay on": "All drives"
        "Configure Solicited Remote Assistance": Disabled
```

### Steps to Reproduce Issue

In the above setup, the "Force a specific default lock screen and logon image" group policy becomes "Not configured" if the highstate is applied. Manually executing states lgpo2,lgpo1 (so in reversed order) _does_ work.

It seems like the second run of `lgpo.set` does not detect the existing setting of "Force a specific ...", and fails to preserve it.

Other Group Policies are fine; the ones that I saw as being affected are ones that take string elements. Another example: the user policy "Desktop Wallpaper".

### Versions Report
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-165-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

Salt minion: 2019.2.2 PY3 on Windows 10 IoT Ent x64 (both 2016 and 2019 editions)

**Comment by waynew** [comment]
@twangboy Does this have anything to do with your LGPO fixes?

**Comment by waynew** [comment]
@onnodb it looks like this is fixed in @twangboy's most recent LGPO fixes - at least when I run it on our testing `2019.2.2.11` windows minions it seems to work as expected.

**Comment by onnodb** [comment]
Thanks for the heads up @waynew! I'll have another look at it coming week, and close the issue if 2019.2.2.11 solves it.

**Comment by onnodb** [comment]
@waynew I've just had a look, using a fresh installation of a 2019.2.3 Salt Minion:
```
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2019
         system: Windows
        version: 2019 10.0.17763 SP0 Multiprocessor Free
```
(I'm a little bit confused about your mention of a 2019.2.2.11 version: I couldn't find such a version on repo.saltstack.com. The latest I could find is 2019.2.3?)

This still shows the issue as described above. A first `lgpo.set` state changes the `Force a specific default lock screen and logon image` group policy. It then gets reset to an "Unconfigured" state during the execution of a second `lgpo.set` state in a different SLS file. 

Note that you really need to go into the Group Policy Editor (`gpedit.msc`) to see this happening. In my case, executing the first state shows the `Force ...` policy correctly set, as expected. Then I execute the second state, run *gpedit* again, and the `Force ...` policy has been reset.

My current workaround is to set certain group policies as the *last* step in the salt process. This works, but is of course fragile.

**Comment by waynew** [comment]
@twangboy was that version actually released or is it only used for https://app.vagrantup.com/saltstack/boxes/cicd-winserver2012r2/versions/1.1.395221829 & the like?

**Comment by sagetherage** [comment]
@twangboy was this part of the LGPO fixes that we ended taking out?

**Comment by sagetherage** [comment]
@onnodb leaving that confusing label until I hear from Shane, but will follow up here.

**Comment by sagetherage** [comment]
@onnodb I apologize I did a terrible job at following up, here. I will do better. Can you confirm this is still an issue and have you been able to upgrade to a new Salt version?

**Comment by onnodb** [comment]
@sagetherage No problem, and thanks for the message! I can confirm that this now works fine; I just checked using Salt 3001.1.
