### ISSUE TITLE
[BUG] salt.utils.vmware.get_service_instance can return unauth'd instance

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#58691]
**Description**

Repeated calls to `salt.utils.vmware.get_service_instance` over time can result in an old service instance object being used after its authentication has expired.

**Setup**

Create a custom runner `/srv/salt/_runners/vmware_auth_test.py`:

```python
import salt.cloud

def minimal():
    cloud_client = salt.cloud.CloudClient(__opts__["conf_file"])
    result = cloud_client.action(fun="list_nodes", provider="my-vsphere-provider")
    return result
```

**Steps to Reproduce the behavior**

Run `salt-run vmware_auth_test.minimal` on a schedule of every couple of hours.  I didn't test this with salt's scheduler directly, it was the Enterprise scheduler.

This will happen not on the first run, but on subsequent ones:

```
Exception occurred in runner vmware_auth_test.minimal: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 904, in get_content
    container_ref, [obj_type], True
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The session is not authenticated.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/var/cache/salt/master/extmods/runners/vmware_auth_test.py", line 5, in minimal
    result = cloud_client.action(fun="list_nodes", provider="my-vsphere-provider")
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 503, in action
    return mapper.do_function(provider, fun, kwargs)
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 1567, in do_function
    return {alias: {driver: self.clouds[fun](call="function")}}
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/vmware.py", line 1997, in list_nodes
    _get_si(), vim.VirtualMachine, vm_properties
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 1069, in get_mors_with_properties
    content = get_content(*content_args, **content_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 910, in get_content
    "{}".format(exc.privilegeId)
salt.exceptions.VMwareApiError: Not enough permissions. Required privilege: System.View
```

**Expected behavior**

Given a proper provider configuration, this should work.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-48-generic
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Additional context**

I think this will fix it, by checking the service instance retrieved from `GetSi()` for current auth instead of just returning it.

```patch
diff --git a/salt/utils/vmware.py b/salt/utils/vmware.py
index 11ade89334..f8bf21df6e 100644
--- a/salt/utils/vmware.py
+++ b/salt/utils/vmware.py
@@ -435,10 +435,8 @@ def get_service_instance(
             # and reconnect
             Disconnect(service_instance)
             service_instance = None
-        else:
-            return service_instance
 
-    if not service_instance:
+    else:
         service_instance = _get_service_instance(
             host, username, password, protocol, port, mechanism, principal, domain
         )
```

**Comment by oeuftete** [comment]
ZD-5191.

**Comment by ggiesen** [comment]
I've hit this repeatedly as well. Have to restart Salt master to clear it.

**Comment by ggiesen** [comment]
Still receiving errors, even after applying the two-line patch in #58803 against 3001.1:

```
[DEBUG   ] Failed to execute 'vmware.list_nodes_min()' while querying for running nodes: Permission to perform this operation was denied.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 282, in _get_service_instance
    mechanism=mechanism,
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 847, in SmartConnect
    sslContext)
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
    httpProxyPort)
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
    httpProxyHost, httpProxyPort)
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 608, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1422, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 318, in _get_service_instance
    mechanism=mechanism,
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 867, in SmartConnect
    mechanism=mechanism)
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 266, in Connect
    keyFile, certFile, thumbprint, sslContext, connectionPoolTimeout)
  File "/usr/lib/python3.6/site-packages/pyVim/connect.py", line 390, in __Login
    x = content.sessionManager.Login(user, pwd, None)
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.NoPermission: (vim.fault.NoPermission) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Permission to perform this operation was denied.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 2367, in run_parallel_map_providers_query
    salt.utils.data.simple_types_filter(cloud.clouds[data["fun"]]()),
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/vmware.py", line 1953, in list_nodes_min
    _get_si(), vim.VirtualMachine, vm_properties
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/vmware.py", line 265, in _get_si
    url, username, password, protocol=protocol, port=port
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 458, in get_service_instance
    host, username, password, protocol, port, mechanism, principal, domain
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 349, in _get_service_instance
    raise salt.exceptions.VMwareConnectionError(err_msg)
salt.exceptions.VMwareConnectionError: Permission to perform this operation was denied.
```

**Comment by oeuftete** [comment]
@ggiesen Can you provide some more context on what you are doing when this happens?  What exactly are you doing, i.e. what are you doing and how (CLI, schedule, as part of an orchestration, via the API, etc.)?  You said you had to restart your master, how long does it take before that becomes necessary?

**Comment by ggiesen** [comment]
Sorry, it actually looks like my previous issue was resolved, and this particular issue genuinely was an authentication error.

**Comment by oeuftete** [comment]
> Sorry, it actually looks like my previous issue was resolved, and this particular issue genuinely was an authentication error.

Thanks for the followup!  That's kind of how it looked to me, but I was open to having taken a wrong turn in the maze when looking at how the service instance objects get made.

**Comment by ggiesen** [comment]
I actually hit this 3 times over the weekend:

Exception occurred in runner cloud.create: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 904, in get_content
    container_ref, [obj_type], True
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.NotAuthenticated: (vim.fault.NotAuthenticated) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The session is not authenticated.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   object = 'vim.Folder:group-d1',
   privilegeId = 'System.View'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 397, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/cloud.py", line 191, in create
    info = client.create(provider, instances, **salt.utils.args.clean_kwargs(**kwargs))
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 428, in create
    ret[name] = salt.utils.data.simple_types_filter(mapper.create(vm_))
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 1242, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/vmware.py", line 2836, in create
    _get_si(), vim.Datacenter, datacenter
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 1016, in get_mor_by_property
    container_ref=container_ref,
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 1069, in get_mors_with_properties
    content = get_content(*content_args, **content_kwargs)
  File "/usr/lib/python3.6/site-packages/salt/utils/vmware.py", line 910, in get_content
    "{}".format(exc.privilegeId)
salt.exceptions.VMwareApiError: Not enough permissions. Required privilege: System.View

**Comment by Dejv56** [comment]
I am using salt.utils.vmware.get_service_instance to create instance object via custom proxy module and still experiencing this problem. I am running v3002.2, but i tried to upgrade utils module to master branch, but problem is persistent.

Proxy minion is returning data for several minutes/hours without a hitch and suddenly i get error as in top post and i need to restart proxy minion to get it working for some time again.
