### ISSUE TITLE
[BUG] publisher acls not applied across syndics

### ISSUE THREAD

**Issue by bzukdatto** [saltstack/salt#60413]
**Description**
Publisher acls are not applied properly when the minions are behind a syndic.  The ACLs only work properly for minions directly connected to the Master of masters.

**Setup**

Following publisher acl file is present in /etc/salt/master.d on both master and syndic.
User exists on both master and syndic

```
publisher_acl:
  user1:
    - '*-dev-server-*':
      - test.ping
      - cmd.script
```

Master of masters with minions connected to both master + syndic

**Steps to Reproduce the behavior**
on master of masters (as user1)
```
# test.ping against a locally connected minion that should NOT be allowed
user1@salt-master:~$ salt server1 test.ping
Authorization error occurred.

# test.ping against a minion connected to master that is should be allowed 
user1@salt-master:~$ salt user-dev-server-1 test.ping
user-dev-server-1:
    True
# test.ping against a minion connected to a syndic that should NOT be allowed
user1@salt-master:~$ salt server2 test.ping
server2:
    True

# test.ping against same minion from the syndic works properly (not allowed)
user1@salt-syndic:~$ salt server2 test.ping
Authentication error occurred.


# logs on syndic show user name is being sent
root@salt-syndic:/etc/salt/master.d# grep user1 /var/log/salt/master
2021-06-21 18:23:00,008 [salt.master      :2492][INFO    ][27325] User user1 Published command test.ping with jid 20210621182259368574

```

**Expected behavior**
Publisher ACLs are enforced across syndics

**Screenshots**

**Versions Report**
<details><summary>
Master/syndic/minion versions
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
**** SALT MASTER VERSIONS ***
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-99-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver


*** SALT SYNDIC VERSIONS ***

Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jul 17 2020, 12:50:27)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-112-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver

*** MINION VERSIONS ***
root@salt-master:/etc/salt/master.d# salt -L  'server1,server2,user-dev-server1' grains.get saltversion
user-dev-server-1:
    3001.6
server1:
    3003
server2:
    3003

```
</details>

**Additional context**

**Comment by bzukdatto** [comment]
Is there any more information I can provide here? Not clear on next steps.

**Comment by garethgreenaway** [comment]
@bzukdatto Thanks for the report. @waynew can you follow on this one?

**Comment by waynew** [comment]
I've started looking into this - haven't quite had enough time to repro, but I've got master/syndic/minions setup. I've got a couple of other issues I'm also working to repro so I may not be able to finish reproducing until next week.

**Comment by waynew** [comment]
@bzukdatto does this also fail for you on 3003.2?

I'm unable to reproduce this.

Here's a zip file with my docker-compose setup.

[60413.zip](https://github.com/saltstack/salt/files/7040762/60413.zip)

```
docker-compose up -d
docker-compose exec syndic salt-syndic -d   # wait for a moment for the service to spin up
docker-compose exec master salt-key -Ay
docker-compose exec syndic salt-key -Ay
```

Then do a `docker compose exec master /bin/bash`. In that container

```
su - dude
salt bob test.ping
salt kevin test.ping
```

The minion `kevin` is directly connected to the master, and does not ping. bob, configured in the acl, works just fine with test.ping.

Note - I *am* running 3003.2, so it's possible that this issue has been fixed since then. But... currently I'm not able to reproduce. :confused:

**Comment by bzukdatto** [comment]
@waynew so, it's not clear from the above, but the test.ping suceeded to both kevin and bob?  The issue I'm seeing is that all requests to minions that are connected to a syndic are allowed, despite the acl saying it shouldn't be (ie, I would expect "salt kevin test.ping" to fail due to the acl.

I have not tested on 3003.2.

I'll try to build out your docker setup and verify as well.

**Comment by waynew** [comment]
No - the ACL worked exactly as expected:

Only the functions and the minions listed in the ACL worked. Everything else returned an authentication error.

**Comment by bzukdatto** [comment]
I tried your configuration and I'm still seeing the same behavior -- if the minion is behind the syndic, acls aren't applied correctly.

This is also running master + syndic at 3003.2

```bob@master-1:~$ cat /etc/salt/master
order_masters: True

external_auth:
  pam:
    bob:
      - minion1:
        - test.ping
publisher_acl:
  bob:
    - minion1:
      - test.ping


root@syndic-1:~# cat /etc/salt/master
syndic_master: master-1
id: syndic-1
external_auth:
  pam:
    bob:
      - minion1:
        - test.ping

publisher_acl:
  bob:
    - .*
      - test.ping


# minion connected directly to master
bob@master-1:~$ salt minion1 test.ping
minion1:
    True
# minion connected to syndic
bob@master-1:~$ salt minion2 test.ping
minion2:
    True

```

**Comment by bzukdatto** [comment]
@waynew has this been verified to work in 3004.1?  I'm still seeing the same issue, but not sure if I'm missing something in my setup:

`
root@use1-salt-master-dev-1:~# dpkg -l | grep salt
ii  salt-common                          3004.1+ds-1                           all          shared libraries that salt requires for all packages
ii  salt-master                          3004.1+ds-1                           all          remote manager to administer servers via salt
ii  salt-minion                          3004.1+ds-1                           all          client package for salt, the distributed remote execution system

root@use1-salt-syndic-dev-1:/etc/salt/pki/minion# dpkg -l |grep salt
ii  salt-api                             3004.1+ds-1                                     all          Generic, modular network access system
ii  salt-common                          3004.1+ds-1                                     all          shared libraries that salt requires for all packages
ii  salt-master                          3004.1+ds-1                                     all          remote manager to administer servers via salt
ii  salt-minion                          3004.1+ds-1                                     all          client package for salt, the distributed remote execution system
ii  salt-syndic                          3004.1+ds-1                                     all          master-of-masters for salt, the distributed remote execution system

from /etc/salt/master:

publisher_acl:
  bob:
    - use1-salt-minion-dev-1:
      - test.ping


bob@use1-salt-master-dev-1:~$ salt use1-salt-minion-dev-2 test.ping
[WARNING ] Failed to open log file, do you have permission to write to /var/log/salt/master?
use1-salt-minion-dev-2:
    True

`
